-- Divinus — seed de mensagens (versículo + reflexão + ação prática)
-- Citações no texto Almeida (domínio público). 9 mensagens por categoria.

insert into public.messages
  (category, verse_text, verse_reference, reflection, practical_action, is_daily, is_active, order_index)
values

-- ANSIEDADE ------------------------------------------------------------
('ansiedade', 'Não andeis ansiosos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus.', 'Filipenses 4:6', 'A ansiedade tenta viver hoje um problema que ainda nem chegou. Você não precisa resolver o ano inteiro agora. Só as próximas horas.', 'Escreva o que te preocupa e marque o que está de fato nas suas mãos hoje.', true, true, 0),
('ansiedade', 'Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo.', 'Mateus 6:34', 'Amanhã vai chegar com a força que precisa pra lidar com amanhã. Hoje só existe hoje.', 'Escolha uma coisa — só uma — para resolver antes de dormir. O resto espera.', true, true, 1),
('ansiedade', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', 'Carregar tudo sozinho não é força, é peso desnecessário. Existe alguém disposto a segurar isso com você.', 'Diga em voz alta, sozinho, o que está pesando — nomear já é o primeiro alívio.', true, true, 2),
('ansiedade', 'Lança sobre o Senhor a tua carga, e ele te sustentará.', 'Salmos 55:22', 'A carga não precisa ser arrastada até o fim sozinha. Existe onde deixar o que pesa demais.', 'Antes de dormir, entregue em oração uma única preocupação específica.', true, true, 3),
('ansiedade', 'Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'A paz que você procura não depende de tudo estar resolvido. Ela chega no meio do caos, não depois dele.', 'Respire fundo três vezes antes de reagir a essa mensagem/situação que te tirou do eixo.', true, true, 4),
('ansiedade', 'Tu conservarás em paz aquele cuja mente está firme em ti.', 'Isaías 26:3', 'A mente dispersa cria tempestade onde não existe. Firmeza não é ausência de dúvida, é onde você escolhe fixar o olhar.', 'Escolha uma frase curta pra repetir hoje sempre que o pensamento acelerar.', true, true, 5),
('ansiedade', 'Nos meus muitos pensamentos dentro de mim, as tuas consolações recreiam a minha alma.', 'Salmos 94:19', 'Pensamento demais também cansa. Nem todo pensamento precisa de resposta imediata.', 'Feche os olhos por um minuto e apenas observe os pensamentos passarem, sem entrar em nenhum.', true, true, 6),
('ansiedade', 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades.', 'Filipenses 4:19', 'A falta que você sente hoje não é a palavra final sobre a sua vida. Existe provisão além do que os olhos alcançam agora.', 'Liste três coisas que já foram supridas essa semana, por menores que pareçam.', true, true, 7),
('ansiedade', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo.', 'Salmos 23:4', 'Vale não é destino, é passagem. E ninguém disse que você atravessa sozinho.', 'Nomeie quem pode caminhar com você essa semana — e chame essa pessoa.', true, true, 8),

-- MEDO -------------------------------------------------------------------
('medo', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.', 'Isaías 41:10', 'O medo cresce na imaginação mais do que na realidade. Companhia muda o tamanho de qualquer ameaça.', 'Escreva exatamente o que você teme — no papel, ele quase sempre fica menor.', true, true, 9),
('medo', 'Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', 'O medo paralisante não é a única voz disponível. Existe também coragem, afeto e domínio — escolha qual ouvir.', 'Dê o primeiro passo mínimo, ainda hoje, na direção do que você tem evitado.', true, true, 10),
('medo', 'Esforça-te, e tem bom ânimo; não pasmes, nem te espantes.', 'Josué 1:9', 'Coragem não é a ausência de medo, é seguir andando com ele do lado. Isso já é o suficiente pra hoje.', 'Faça a ligação, mande a mensagem ou marque a conversa que você vem adiando por medo.', true, true, 11),
('medo', 'O Senhor é a minha luz e a minha salvação; a quem temerei?', 'Salmos 27:1', 'Quando a luz vem de outro lugar, o escuro perde poder de assombrar.', 'Antes de dormir, agradeça por uma coisa específica que deu certo apesar do medo.', true, true, 12),
('medo', 'Busquei ao Senhor, e ele me respondeu, e me livrou de todos os meus temores.', 'Salmos 34:4', 'Buscar ajuda não é fraqueza, é a atitude de quem já entendeu que não precisa vencer sozinho.', 'Procure alguém de confiança e conte, em voz alta, do que você tem medo.', true, true, 13),
('medo', 'Esforça-te, e tem bom ânimo; não temas, nem te espantes diante deles.', 'Deuteronômio 31:6', 'A situação difícil à sua frente não muda de tamanho, mas você pode mudar de postura diante dela.', 'Escreva uma frase de ânimo e deixe em algum lugar que você vai ver amanhã de manhã.', true, true, 14),
('medo', 'No amor não há temor, antes o perfeito amor lança fora o temor.', '1 João 4:18', 'Muito medo nasce da dúvida sobre ser amado o bastante. Ser lembrado disso já muda a postura do dia.', 'Reserve cinco minutos pra lembrar de alguém que já provou que te ama de verdade.', true, true, 15),
('medo', 'Em que dia eu temer, hei de confiar em ti.', 'Salmos 56:3', 'O medo pode aparecer hoje — a questão não é se ele vem, é pra onde você olha quando ele chega.', 'Quando o medo bater hoje, diga em voz alta: "ainda assim, eu confio."', true, true, 16),
('medo', 'Não temas, porque eu te resgatei; quando passares pelas águas, eu serei contigo.', 'Isaías 43:1-2', 'A travessia difícil não é prometida sem companhia. Água funda não é sinônimo de afogamento.', 'Identifique em qual "água" você está agora e peça, especificamente, por travessia — não por atalho.', true, true, 17),

-- FRUSTRAÇÃO --------------------------------------------------------------
('frustracao', 'Tende grande gozo quando cairdes em várias tentações, sabendo que a prova da vossa fé produz a paciência.', 'Tiago 1:2-4', 'O que hoje parece perda de tempo pode estar formando algo que você só vai reconhecer depois.', 'Escreva uma coisa que essa dificuldade já ensinou, mesmo que ainda doa.', true, true, 18),
('frustracao', 'Todas as coisas contribuem juntamente para o bem daqueles que amam a Deus.', 'Romanos 8:28', 'Nem tudo que acontece parece bom no momento em que acontece. Mas nem tudo que acontece é o fim da história.', 'Releia uma frustração antiga que hoje já não pesa mais — sirva de lembrete.', true, true, 19),
('frustracao', 'Não nos cansemos de fazer o bem, pois a seu tempo ceifaremos, se não houvermos desfalecido.', 'Gálatas 6:9', 'Cansar no meio do caminho é humano. Desistir de vez é que muda o resultado.', 'Faça hoje só mais um pouquinho do que você queria desistir — nem que seja o mínimo.', true, true, 20),
('frustracao', 'Descansa no Senhor, e espera nele; não te enfades por causa daquele que prospera no seu caminho.', 'Salmos 37:7', 'Comparar seu tempo com o tempo do outro só aumenta a impaciência. Cada colheita tem sua estação.', 'Desligue, por hoje, de qualquer coisa que te faça comparar sua caminhada com a de outra pessoa.', true, true, 21),
('frustracao', 'Muitos são os pensamentos no coração do homem, mas o conselho do Senhor permanecerá.', 'Provérbios 19:21', 'Seu plano não deu certo como você esperava — isso não significa que não exista um plano melhor em andamento.', 'Anote um plano B simples pro que não saiu como você queria.', true, true, 22),
('frustracao', 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.', 'Eclesiastes 3:1', 'Frustração muitas vezes é impaciência com o relógio errado — o seu, não o certo.', 'Pergunte-se: isso que me frustra hoje ainda vai importar em um ano?', true, true, 23),
('frustracao', 'A tribulação produz a paciência; e a paciência, a experiência; e a experiência, a esperança.', 'Romanos 5:3-4', 'A dificuldade de hoje está construindo uma capacidade que você ainda não tem. É desconfortável, mas não é inútil.', 'Nomeie uma força que você desenvolveu justamente por causa de uma dificuldade parecida com essa.', true, true, 24),
('frustracao', 'Esperei com paciência no Senhor, e ele se inclinou para mim, e ouviu o meu clamor.', 'Salmos 40:1', 'Esperar sem resposta imediata não é ser ignorado. É estar no meio de um processo que ainda não terminou.', 'Marque uma data pra reavaliar essa situação — e solte o controle até lá.', true, true, 25),
('frustracao', 'Corramos com paciência a carreira que nos está proposta.', 'Hebreus 12:1', 'Você não precisa correr no ritmo de ninguém além do seu. A corrida é sua.', 'Reduza o ritmo de uma tarefa hoje só pra fazer com mais presença, não mais pressa.', true, true, 26),

-- FALTA DE DIREÇÃO ---------------------------------------------------------
('falta_de_direcao', 'Confia no Senhor de todo o teu coração... e ele endireitará as tuas veredas.', 'Provérbios 3:5-6', 'Não ter o mapa inteiro não significa estar perdido. Significa que o próximo passo já é suficiente por agora.', 'Dê só o próximo passo óbvio — não o passo dez, o passo um.', true, true, 27),
('falta_de_direcao', 'Instruir-te-ei, e te ensinarei o caminho que deves seguir.', 'Salmos 32:8', 'Direção costuma chegar andando, não parada. Movimento revela caminho.', 'Escolha uma direção possível hoje, mesmo sem certeza total, e ande um pouco nela.', true, true, 28),
('falta_de_direcao', 'Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.', 'Salmos 119:105', 'A luz que você tem hoje ilumina só o próximo passo, não a estrada inteira — e está certo assim.', 'Pergunte a alguém que já passou por decisão parecida como foi o processo dela.', true, true, 29),
('falta_de_direcao', 'Se algum de vós tem falta de sabedoria, peça-a a Deus, e ser-lhe-á dada.', 'Tiago 1:5', 'Não saber o que fazer não é falha, é o momento certo de pedir clareza em vez de fingir que já sabe.', 'Escreva a pergunta real por trás da indecisão — às vezes ela muda tudo.', true, true, 30),
('falta_de_direcao', 'Este é o caminho, andai nele.', 'Isaías 30:21', 'Existe uma voz de orientação disponível quando o barulho externo diminui.', 'Reserve dez minutos de silêncio, sem tela, só pra pensar com clareza.', true, true, 31),
('falta_de_direcao', 'Pelo Senhor são ordenados os passos do homem bom.', 'Salmos 37:23', 'Os passos que parecem desconexos hoje podem fazer sentido só quando olhados de longe, depois.', 'Olhe pra trás e note um passo que na hora parecia errado e hoje faz sentido.', true, true, 32),
('falta_de_direcao', 'O coração do homem propõe o seu caminho, mas o Senhor lhe dirige os passos.', 'Provérbios 16:9', 'Planejar é seu trabalho. Controlar cada resultado, não é.', 'Faça um plano simples pra semana e deixe espaço pro imprevisto sem culpa.', true, true, 33),
('falta_de_direcao', 'Eu bem sei os pensamentos que penso de vós... pensamentos de paz, e não de mal.', 'Jeremias 29:11', 'A incerteza sobre o futuro não significa que ele seja ruim. Só significa que ainda não chegou.', 'Escreva uma frase sobre onde você quer estar daqui um ano — sem cobrança, só direção.', true, true, 34),
('falta_de_direcao', 'Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas.', 'Salmos 25:4-5', 'Pedir orientação é mais honesto do que fingir ter tudo sob controle.', 'Antes de decidir algo importante hoje, pare e peça clareza antes de agir.', true, true, 35),

-- LUTO ---------------------------------------------------------------------
('luto', 'Perto está o Senhor dos que têm o coração quebrantado.', 'Salmos 34:18', 'A dor da perda não precisa ser escondida pra ser suportável. Proximidade importa mais que explicação.', 'Permita-se chorar hoje sem pressa de "estar melhor" até uma data específica.', true, true, 36),
('luto', 'Bem-aventurados os que choram, porque eles serão consolados.', 'Mateus 5:4', 'Chorar não é fraqueza nem falta de fé — é parte de atravessar a dor de verdade.', 'Ligue pra alguém que também sentiu essa falta e divida a lembrança com essa pessoa.', true, true, 37),
('luto', 'Deus limpará de seus olhos toda a lágrima; não haverá mais morte, nem pranto.', 'Apocalipse 21:4', 'A dor de hoje não é a versão final da história. Existe um horizonte onde ela não pesa mais.', 'Escreva uma memória boa da pessoa ou fase que você perdeu — guarde, não apague.', true, true, 38),
('luto', 'Sara os quebrantados de coração, e liga-lhes as feridas.', 'Salmos 147:3', 'Uma ferida coberta rápido demais volta a doer. Cura de verdade leva tempo, e tudo bem.', 'Não se cobre por ainda estar triste. Dê a si mesmo o prazo que a dor pedir.', true, true, 39),
('luto', 'Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá.', 'João 11:25', 'A perda parece definitiva, mas a fé aponta pra além do que os olhos alcançam agora.', 'Acenda uma vela ou escreva uma carta pra quem se foi — dar forma à saudade ajuda a carregar.', true, true, 40),
('luto', 'Deus... nos consola em toda a nossa tribulação.', '2 Coríntios 1:3-4', 'Quem já foi consolado sabe consolar melhor. Sua dor de hoje pode virar cuidado por alguém amanhã.', 'Procure alguém que também está de luto essa semana, só pra fazer companhia.', true, true, 41),
('luto', 'O choro pode durar uma noite, mas a alegria vem pela manhã.', 'Salmos 30:5', 'A noite comprida de hoje não é a manhã inteira. Ela tem hora de acabar, mesmo que você não veja o relógio ainda.', 'Marque no calendário algo pequeno pra daqui uma semana — um motivo simples pra seguir.', true, true, 42),
('luto', 'Dar-lhes coroa em vez de cinza, óleo de gozo em vez de tristeza.', 'Isaías 61:3', 'Da cinza mais espessa já nasceu recomeço. Isso não apaga a perda, mas convive com ela.', 'Faça algo pequeno hoje em homenagem a quem ou ao que você perdeu.', true, true, 43),
('luto', 'Preciosa é aos olhos do Senhor a morte dos seus santos.', 'Salmos 116:15', 'A vida que se foi teve valor — e continua tendo, mesmo na ausência.', 'Conte pra alguém mais novo uma história boa de quem partiu — mantenha viva a lembrança.', true, true, 44),

-- SOLIDÃO --------------------------------------------------------------------
('solidao', 'O Senhor é aquele que vai adiante de ti; ele será contigo, não te deixará.', 'Deuteronômio 31:8', 'Ninguém por perto agora não é o mesmo que estar sozinho pra sempre. Companhia às vezes chega antes de ser vista.', 'Mande uma mensagem simples pra alguém que você não fala há tempo.', true, true, 45),
('solidao', 'Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'A sensação de abandono não é a palavra final sobre a sua situação.', 'Escreva um lembrete visível: "eu não estou tão sozinho quanto sinto agora."', true, true, 46),
('solidao', 'Deus faz que o solitário viva em família.', 'Salmos 68:6', 'Família nem sempre é sangue. Às vezes ela se forma no tempo certo, com as pessoas certas.', 'Aceite (ou marque) um convite que você vinha recusando por comodismo ou medo.', true, true, 47),
('solidao', 'Eu estou convosco todos os dias, até à consumação dos séculos.', 'Mateus 28:20', 'Presença constante não depende de estar visível o tempo todo.', 'Reserve um momento hoje só pra estar em silêncio, sem preencher com tela ou ruído.', true, true, 48),
('solidao', 'Olha para mim, e tem misericórdia de mim, porque estou solitário e aflito.', 'Salmos 25:16', 'Admitir a solidão em voz alta já é diferente de carregá-la calado.', 'Diga pra uma pessoa de confiança, sem rodeio: "eu tenho me sentido sozinho".', true, true, 49),
('solidao', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'Uma ausência temporária não é a mesma coisa que abandono definitivo.', 'Marque um encontro presencial essa semana, mesmo que pequeno.', true, true, 50),
('solidao', 'O Senhor teu Deus está no meio de ti.', 'Sofonias 3:17', 'Vazio de gente ao redor não é o mesmo que vazio por dentro.', 'Antes de dormir, nomeie uma presença boa que passou pelo seu dia, por menor que tenha sido.', true, true, 51),
('solidao', 'Há amigo mais chegado que um irmão.', 'Provérbios 18:24', 'Nem toda solidão se resolve com mais gente — às vezes precisa de uma pessoa certa, não de muitas.', 'Invista tempo essa semana numa única amizade que vale a pena aprofundar.', true, true, 52),
('solidao', 'Quando meu pai e minha mãe me desampararem, o Senhor me recolherá.', 'Salmos 27:10', 'Mesmo quando quem deveria ficar se afasta, existe um lugar de acolhimento que permanece.', 'Escreva o que você precisava ouvir de alguém hoje — e diga isso a si mesmo em voz alta.', true, true, 53),

-- RELACIONAMENTOS --------------------------------------------------------------
('relacionamentos', 'O amor é sofredor, é benigno... tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:4-7', 'Amor de verdade aguenta o atrito do dia a dia sem virar guerra.', 'Escolha ceder num detalhe pequeno hoje numa discussão que não precisa ser vencida.', true, true, 54),
('relacionamentos', 'Sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros.', 'Efésios 4:32', 'Guardar mágoa cansa mais quem guarda do que quem errou.', 'Mande uma mensagem de paz pra alguém com quem você está em silêncio por orgulho.', true, true, 55),
('relacionamentos', 'Suportando-vos uns aos outros, e perdoando-vos uns aos outros.', 'Colossenses 3:13', 'Toda relação boa sobrevive porque alguém decide perdoar antes de estar pronto pra isso.', 'Identifique uma mágoa pequena que já pode ser solta hoje.', true, true, 56),
('relacionamentos', 'Em todo o tempo ama o amigo.', 'Provérbios 17:17', 'Amizade de verdade não depende da fase boa — ela atravessa também a fase ruim.', 'Ligue (não mande só mensagem) pra um amigo que está numa fase difícil.', true, true, 57),
('relacionamentos', 'Amai-vos cordialmente uns aos outros com amor fraternal.', 'Romanos 12:10', 'Afeto verdadeiro se mostra em gesto, não só em sentimento guardado.', 'Diga em voz alta, hoje, o que você valoriza numa pessoa próxima — sem esperar ocasião especial.', true, true, 58),
('relacionamentos', 'Melhor é serem dois do que um... porque, se um cair, o outro o levanta.', 'Eclesiastes 4:9-10', 'Ninguém foi feito pra atravessar tudo sozinho. Pedir apoio é maturidade, não fraqueza.', 'Peça ajuda concreta com algo que você vem tentando resolver sozinho.', true, true, 59),
('relacionamentos', 'Todo o homem seja pronto para ouvir, tardio para falar.', 'Tiago 1:19', 'Muita briga nasce de resposta rápida demais e escuta de menos.', 'Na próxima conversa difícil hoje, escute até o fim antes de responder.', true, true, 60),
('relacionamentos', 'A resposta branda desvia o furor.', 'Provérbios 15:1', 'O tom da resposta muda o rumo da conversa mais do que o conteúdo dela.', 'Reescreva mentalmente uma resposta difícil num tom mais calmo antes de enviar.', true, true, 61),
('relacionamentos', 'O amor cobre a multidão de pecados.', '1 Pedro 4:8', 'Ninguém é perfeito o suficiente pra merecer um amor sem falhas — por isso ele cobre, não ignora.', 'Escolha não repetir hoje um erro antigo de alguém que já foi perdoado.', true, true, 62),

-- PROPÓSITO --------------------------------------------------------------------
('proposito', 'Somos feitura sua, criados em Cristo Jesus para as boas obras.', 'Efésios 2:10', 'Você não é um acidente nem um acréscimo — existe intenção por trás de quem você é.', 'Escreva uma coisa boa que só você, do seu jeito, consegue fazer por alguém.', true, true, 63),
('proposito', 'Quem sabe se para tal tempo como este chegaste a este lugar?', 'Ester 4:14', 'A posição em que você está agora pode não ser coincidência, mas preparo.', 'Pergunte-se: o que essa fase específica pode estar me preparando pra fazer?', true, true, 64),
('proposito', 'Te louvarei, porque de um modo assombroso, e tão maravilhoso fui feito.', 'Salmos 139:14', 'Antes de qualquer conquista, já existe valor em quem você é.', 'Escreva três características suas que não dependem de resultado nenhum pra valer.', true, true, 65),
('proposito', 'Aquele que em vós começou a boa obra a aperfeiçoará.', 'Filipenses 1:6', 'Você não precisa estar pronto hoje. Estar em processo já é parte do plano.', 'Olhe pra trás e note o quanto você já mudou nos últimos anos — o processo está ativo.', true, true, 66),
('proposito', 'Vós sois a geração eleita... para anunciardes as virtudes daquele que vos chamou.', '1 Pedro 2:9', 'Existe um chamado maior que a rotina — e ele passa pela rotina, não fora dela.', 'Encontre um jeito de fazer bem, hoje, uma tarefa comum que parecia sem sentido.', true, true, 67),
('proposito', 'Tudo o que fizerdes, fazei-o de todo o coração, como ao Senhor.', 'Colossenses 3:23', 'Trabalho pequeno feito por inteiro pesa mais do que trabalho grande feito pela metade.', 'Escolha uma tarefa comum hoje e faça com o dobro do cuidado de costume.', true, true, 68),
('proposito', 'Assim resplandeça a vossa luz diante dos homens.', 'Mateus 5:16', 'Você não precisa gritar pra ser notado — viver bem já é uma forma de mensagem.', 'Faça hoje um gesto de bem sem anunciar pra ninguém.', true, true, 69),
('proposito', 'Fomos feitos herança, segundo o propósito daquele que faz todas as coisas.', 'Efésios 1:11', 'Nada do que você vive é desperdiçado — mesmo o difícil entra na formação do propósito.', 'Liste uma dificuldade passada que hoje faz parte da sua força atual.', true, true, 70),
('proposito', 'Transformai-vos pela renovação do vosso entendimento, para que experimenteis a boa e perfeita vontade de Deus.', 'Romanos 12:2', 'Propósito não aparece de uma vez — ele se revela conforme a mente se renova.', 'Troque hoje um pensamento automático negativo por uma frase mais verdadeira sobre você.', true, true, 71),

-- DISCIPLINA --------------------------------------------------------------------
('disciplina', 'Sujeito o meu corpo, e o reduzo à servidão.', '1 Coríntios 9:27', 'Disciplina não é castigo, é decidir hoje o que seu futuro vai agradecer.', 'Faça agora a tarefa que você vem adiando há mais tempo, mesmo que pequena.', true, true, 72),
('disciplina', 'Como a cidade derribada, que não tem muros, assim é o homem que não pode conter o seu espírito.', 'Provérbios 25:28', 'Limite não é prisão — é o que sustenta o que você está construindo.', 'Defina um limite simples pra hoje (hora de dormir, tempo de tela, o que for) e cumpra.', true, true, 73),
('disciplina', 'O fruto do Espírito é... domínio próprio.', 'Gálatas 5:22-23', 'Domínio próprio não nasce pronto — ele se treina em decisões pequenas repetidas.', 'Escolha uma reação automática hoje e responda diferente do de costume.', true, true, 74),
('disciplina', 'Toda a disciplina, ao presente, não parece motivo de gozo, mas depois produz um fruto pacífico.', 'Hebreus 12:11', 'O desconforto de hoje treinando algo difícil não é sinal de erro — é parte do processo.', 'Continue por mais quinze minutos numa tarefa difícil antes de parar.', true, true, 75),
('disciplina', 'Confia ao Senhor as tuas obras, e teus pensamentos serão bem-sucedidos.', 'Provérbios 16:3', 'Planejamento com propósito rende mais do que esforço sem direção.', 'Escreva o plano de amanhã antes de dormir hoje.', true, true, 76),
('disciplina', 'Prossigo para o alvo, pelo prêmio da soberana vocação.', 'Filipenses 3:14', 'Constância importa mais que intensidade — poucos passos todos os dias vencem muitos passos só às vezes.', 'Repita hoje o mesmo hábito bom de ontem, sem pular por cansaço.', true, true, 77),
('disciplina', 'Não sabeis que o vosso corpo é o templo do Espírito Santo?', '1 Coríntios 6:19-20', 'Cuidar do corpo também é uma forma de disciplina espiritual, não só estética.', 'Beba água, durma cedo ou se movimente hoje — escolha um cuidado concreto com o corpo.', true, true, 78),
('disciplina', 'Os pensamentos do diligente tendem só para a abundância.', 'Provérbios 21:5', 'Pressa sem plano gasta energia à toa. Constância com direção rende mais.', 'Antes de agir por impulso hoje, pare trinta segundos e pense no próximo passo certo.', true, true, 79),
('disciplina', 'Vivamos neste presente século sóbria, e justa, e piamente.', 'Tito 2:12', 'Sobriedade é escolher o que edifica em vez do que só distrai por agora.', 'Troque um hábito de distração hoje por dez minutos de algo que constrói.', true, true, 80),

-- RECOMEÇO --------------------------------------------------------------------
('recomeco', 'Não vos lembreis das coisas passadas... eis que faço uma coisa nova.', 'Isaías 43:18-19', 'O que ficou pra trás não precisa ser carregado pra dentro do que vem agora.', 'Escreva uma coisa do passado que você está disposto a soltar hoje.', true, true, 81),
('recomeco', 'Se alguém está em Cristo, nova criatura é: as coisas velhas já passaram.', '2 Coríntios 5:17', 'Recomeçar não é fingir que nada aconteceu — é seguir sendo alguém diferente do que era.', 'Dê o primeiro passo concreto de algo que você vem adiando "começar de novo".', true, true, 82),
('recomeco', 'As suas misericórdias se renovam cada manhã.', 'Lamentações 3:22-23', 'Você não precisa esperar o ano virar pra começar de novo. Cada manhã já é uma chance nova.', 'Trate essa manhã como um recomeço real, sem carregar o peso de ontem.', true, true, 83),
('recomeco', 'Esquecendo-me das coisas que atrás ficam, prossigo para o alvo.', 'Filipenses 3:13', 'Olhar pra frente não apaga o passado, mas impede que ele dite o próximo passo.', 'Escreva o próximo passo, não o último erro.', true, true, 84),
('recomeco', 'Eis que faço novas todas as coisas.', 'Apocalipse 21:5', 'Nada está tão quebrado que não caiba em um recomeço.', 'Comece hoje, mesmo pequeno, algo que você tinha certeza que era tarde demais pra começar.', true, true, 85),
('recomeco', 'Restituir-vos-ei os anos que foram comidos pelo gafanhoto.', 'Joel 2:25', 'Tempo perdido não é tempo definitivo — existe restauração possível, mesmo tarde.', 'Volte hoje a algo bom que você abandonou por tempo demais.', true, true, 86),
('recomeco', 'Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto.', 'Salmos 51:10', 'Recomeço de verdade começa por dentro, antes de aparecer por fora.', 'Reserve um momento hoje só pra pedir clareza e limpeza interior, sem pressa de resultado.', true, true, 87),
('recomeco', 'Vos darei coração novo, e porei dentro de vós espírito novo.', 'Ezequiel 36:26', 'Mudança de verdade não é só de comportamento — é de raiz.', 'Identifique a raiz (não só o sintoma) do que você quer mudar, e comece por ali.', true, true, 88),
('recomeco', 'Sete vezes cai o justo, e se levanta.', 'Provérbios 24:16', 'Cair de novo não anula os recomeços anteriores. Levantar de novo é que conta.', 'Se você caiu numa recaída, não espere segunda-feira — recomece agora mesmo.', true, true, 89)
;
