-- Divinus — segunda leva de mensagens do hero (74 mensagens adicionais)

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Enquanto a cidade caía atrás dela, uma mulher parou pra olhar o que estava deixando pra trás — e essa pausa custou tudo.', 'lot-nao-olhou-para-tras', 'Gênesis 19:15-26', 'Lot e sua família são retirados de Sodoma antes da destruição da cidade, com uma instrução clara dos anjos: fugir sem olhar para trás.', 'No caminho, a esposa de Lot olha para trás — talvez por saudade, talvez por dúvida — e se torna uma estátua de sal. O texto não detalha o motivo, só a consequência de hesitar no meio de uma saída necessária.', 'Algumas saídas exigem não olhar para o que está sendo deixado para trás, pelo menos não agora. Meio caminho entre o velho e o novo é o lugar mais perigoso para parar.', 'Lucas 9:62 traz o mesmo princípio: quem põe a mão no arado e olha para trás não é apto para o Reino.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Fugindo de casa sozinho e sem nada, ele dormiu numa pedra e sonhou com uma escada até o céu — o lugar mais desamparado virou onde Deus se revelou.', 'escada-de-jaco', 'Gênesis 28:10-19', 'Jacó foge de Esaú, sozinho, sem provisão, dormindo ao relento com uma pedra como travesseiro — um dos pontos mais baixos de sua vida até ali.', 'Ele sonha com uma escada ligando terra e céu, anjos subindo e descendo, e Deus reafirmando a mesma promessa feita a Abraão. Jacó acorda dizendo: "o Senhor está neste lugar, e eu não o sabia".', 'Presença divina não espera você estar num lugar bonito ou preparado para recebê-la. Pode aparecer exatamente no ponto mais desamparado da fuga.', 'João 1:51 retoma essa imagem: Jesus se descreve como o novo ponto de conexão entre céu e terra.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Faminto depois de um dia de caça, ele trocou o direito de nascença por um prato de comida — e só percebeu o tamanho da perda tempos depois.', 'esau-vendeu-a-primogenitura', 'Gênesis 25:29-34', 'Esaú, o filho mais velho de Isaque, chega faminto do campo e encontra Jacó cozinhando um ensopado, que se recusa a dividir sem receber a primogenitura em troca.', 'Esaú desdenha o próprio direito de nascença dizendo "de que me serve a primogenitura?", trocando um benefício de longo prazo por alívio imediato. O texto resume secamente: "assim desprezou Esaú o seu direito de primogenitura".', 'Decisões tomadas no auge da fome, do cansaço ou da urgência costumam trocar barato algo que só se percebe caro depois.', 'Hebreus 12:16-17 cita esse episódio como aviso: depois, mesmo chorando, Esaú não encontrou como reverter a troca.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um rei-sacerdote sem genealogia registrada aparece do nada pra abençoar um homem, recebe um décimo do que ele tinha, e desaparece da história.', 'melquisedeque-abencoa-abraao', 'Gênesis 14:17-20', 'Depois de vencer uma coalizão de reis para resgatar seu sobrinho Ló, Abraão é recebido por Melquisedeque, rei de Salém e "sacerdote do Deus Altíssimo" — figura sem antecedentes na narrativa.', 'Melquisedeque traz pão e vinho, abençoa Abraão, e Abraão lhe entrega o dízimo de tudo que tinha capturado. É um encontro breve, mas carregado de peso simbólico dentro do texto.', 'Nem toda figura significativa na sua história precisa de uma introdução longa. Às vezes uma bênção decisiva vem de alguém que aparece uma única vez.', 'Hebreus 7 usa Melquisedeque como figura antecipada de Cristo, um sacerdócio que não depende de linhagem.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('O povo foi mordido por cobras depois de reclamar demais no deserto — e a cura pedida não era remédio, era simplesmente olhar pra cima.', 'serpente-de-bronze', 'Números 21:4-9', 'Depois de reclamações contínuas no deserto sobre comida e água, cobras venenosas atacam o acampamento, e o povo reconhece o próprio erro, pedindo intercessão a Moisés.', 'Deus manda Moisés erguer uma serpente de bronze num mastro: quem fosse mordido e olhasse para ela sobrevivia. A cura não exigia esforço, exigia direção — olhar para o lugar certo.', 'Às vezes a saída de uma crise que você mesmo causou não pede grande esforço — pede só a humildade de olhar na direção certa em vez de continuar remoendo o problema.', 'João 3:14-15 usa essa cena diretamente: assim como a serpente foi levantada, também o Filho do Homem seria, para quem olhar para ele viver.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um profeta pago para amaldiçoar seguia tranquilo em sua jumenta até o animal parar, enxergando o que o próprio profeta não conseguia ver.', 'jumenta-de-balaao-fala', 'Números 22:21-35', 'Balaão, profeta contratado por um rei inimigo para amaldiçoar Israel, viaja montado numa jumenta, movido por ganância mais do que por real convicção sobre a missão.', 'No caminho, um anjo com espada aparece três vezes só visível para a jumenta, que empaca e desvia repetidamente. Balaão bate no animal com raiva até a jumenta falar, questionando o próprio tratamento — só então os olhos de Balaão se abrem para o anjo.', 'Às vezes o obstáculo que te irrita no caminho está, na verdade, te protegendo de algo que você ainda não consegue enxergar.', '2 Pedro 2:16 lembra esse episódio como exemplo de correção vinda de um lugar totalmente inesperado.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('No fim de um discurso longo, a instrução final foi simples: de um lado vida e bênção, do outro morte e maldição — e a escolha era genuinamente livre.', 'escolhe-a-vida', 'Deuteronômio 30:15-20', 'Moisés, no fim de sua vida, entrega ao povo de Israel um último discurso antes de entrarem na terra prometida sem ele, resumindo décadas de lei e história.', 'Ele apresenta duas direções claramente opostas — vida e bem, morte e mal — e conclui: "escolhe, pois, a vida, para que vivas, tu e a tua descendência". A escolha não é forçada, é apresentada com urgência e clareza.', 'Clareza sobre as duas direções possíveis não elimina a necessidade de escolher ativamente uma delas, todos os dias.', 'Mateus 7:13-14 traz a mesma estrutura de duas portas, duas estradas, dois destinos diferentes.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Numa época sem líderes claros, uma mulher julgava debaixo de uma palmeira, e foi até o campo de batalha porque um general não teve coragem de ir sozinho.', 'debora-julgou-sob-a-palmeira', 'Juízes 4', 'Débora era profetisa e juíza de Israel num período de opressão cananeia, julgando disputas debaixo de uma palmeira que levava seu nome, quando convoca Baraque para liderar a batalha.', 'Baraque só aceita ir se Débora for junto, e ela concorda, mas avisa que a honra da vitória final iria para uma mulher, não para ele. A batalha é vencida, e uma segunda mulher, Jael, encerra o conflito matando o general inimigo.', 'Liderança não depende de estar na posição mais visível — às vezes é quem convoca e caminha ao lado que sustenta a coragem de quem está à frente.', '1 Coríntios 1:27 confirma o padrão: força vinda de onde menos se espera, para que ninguém se glorie sozinho.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('O filho do rei tinha todos os motivos para ver o outro como ameaça ao próprio trono — e escolheu, em vez disso, ser o amigo mais leal que ele teve.', 'davi-e-jonatas-alianca', '1 Samuel 18-20', 'Jônatas, filho do rei Saul e herdeiro natural do trono, desenvolve uma amizade profunda com Davi logo depois da vitória sobre Golias, mesmo sabendo que Davi seria o próximo rei em seu lugar.', 'Jônatas faz aliança com Davi, dá a ele suas próprias vestes e armas — gestos de renúncia ao próprio direito — e mais tarde arrisca a vida avisando Davi sobre os planos assassinos de Saul.', 'Amizade genuína às vezes exige abrir mão do próprio interesse em favor do bem do outro, mesmo quando isso custa status ou vantagem pessoal.', 'João 15:13 define o padrão máximo dessa amizade: "ninguém tem maior amor do que este, de dar alguém a sua vida pelos seus amigos".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('O rei dançou em público com tanta entrega que a própria esposa se envergonhou dele — e ele preferiu parecer indigno a conter a alegria genuína.', 'davi-dancou-diante-da-arca', '2 Samuel 6:12-23', 'Davi traz a arca da aliança de volta a Jerusalém, um momento de celebração nacional depois de anos sem o símbolo central da presença de Deus estar com o povo.', 'Davi dança "com todas as forças" diante da arca, vestido de forma simples, sem se preocupar com a própria dignidade real. Sua esposa Mical o despreza por isso, e Davi responde que preferia se humilhar ainda mais aos olhos dela do que diante de Deus.', 'Adoração genuína às vezes parece exagerada demais para quem está de fora olhando com julgamento. Isso não a torna menos verdadeira.', 'Salmos 149:3 convida à mesma expressão física de alegria: louvar dançando, não só em silêncio contido.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Mesmo depois de o próprio filho liderar uma rebelião armada contra ele, ao saber da morte dele o rei chorou como se tivesse perdido tudo.', 'absalao-e-o-luto-de-davi', '2 Samuel 18:31-33', 'Absalão, filho de Davi, se rebela contra o pai e tenta tomar o trono à força, numa guerra civil que divide o reino e força Davi a fugir da própria capital.', 'Quando as tropas de Davi vencem e Absalão morre, a reação do rei não é alívio — é um dos lamentos mais crus da Bíblia: "meu filho Absalão, meu filho, meu filho Absalão! Quem me dera que eu morrera por ti".', 'Amor por alguém que causou dano profundo não desaparece automaticamente. As duas coisas — a ferida e o amor — podem coexistir na mesma pessoa.', 'Lucas 15:20 mostra o mesmo tipo de amor que corre ao encontro, mesmo depois de rebelião e afastamento.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Depois de anos de construção, no dia da inauguração, o próprio rei que mandou construir se ajoelhou em público e admitiu que nenhuma casa seria grande o bastante para conter Deus.', 'dedicacao-do-templo', '1 Reis 8', 'Salomão termina de construir o templo em Jerusalém, sete anos de obra, e organiza a cerimônia de dedicação diante de todo o povo reunido.', 'No auge da celebração, Salomão ora publicamente reconhecendo que nem os céus mais altos poderiam conter Deus, muito menos um templo construído por mãos humanas — e pede que Deus ouça as orações feitas naquele lugar, vindas de qualquer pessoa, inclusive estrangeiros.', 'Construir algo grande e importante não é o mesmo que possuir ou limitar aquilo que esse algo representa. Humildade cabe até no auge da própria conquista.', 'Atos 7:48-49 retoma essa ideia: o Altíssimo não habita em templos feitos por mãos humanas.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ela viajou de muito longe só para checar se os relatos sobre a sabedoria dele eram exagero — e saiu dizendo que nem a metade tinha sido contada.', 'rainha-de-saba-veio-conferir', '1 Reis 10:1-13', 'A rainha de Sabá ouve sobre a fama e a sabedoria de Salomão e viaja com uma grande comitiva, trazendo especiarias, ouro e pedras preciosas, para testá-lo com perguntas difíceis.', 'Depois de ver a sabedoria de Salomão em ação, a organização de sua corte e a prosperidade do reino, ela declara que a realidade superava tudo que tinha ouvido contar, e reconhece publicamente a bênção de Deus sobre ele.', 'Reputação construída sobre substância real, mais cedo ou mais tarde, resiste até ao escrutínio mais cético.', 'Mateus 12:42 cita esse episódio: uma estrangeira reconheceu sabedoria que muitos dos contemporâneos de Jesus recusaram reconhecer nele.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ela tinha farinha e azeite pra uma última refeição antes de morrer de fome com o filho, e ainda assim dividiu o pouco que tinha com um estranho faminto.', 'viuva-de-sarepta', '1 Reis 17:8-16', 'Durante uma seca severa enviada como julgamento, Elias é enviado a uma viúva estrangeira em Sarepta, que se prepara para fazer a última refeição antes de morrer de fome junto com o filho.', 'Elias pede que ela primeiro faça um bolo para ele antes de cuidar de si mesma, prometendo que a farinha e o azeite não acabariam até a chuva voltar. Ela obedece, apesar do medo, e a provisão se sustenta durante toda a seca.', 'Generosidade no momento de maior escassez pessoal parece loucura pela lógica comum — e é exatamente aí que a provisão às vezes se revela.', 'Lucas 4:25-26 lembra que, entre todas as viúvas de Israel na época, foi justamente essa estrangeira que recebeu o milagre.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um homem pobre chorou por ter perdido um machado emprestado — um problema pequeno demais pra a maioria — e recebeu atenção do profeta mesmo assim.', 'machado-que-flutuou', '2 Reis 6:1-7', 'Um grupo de discípulos dos profetas está construindo moradias maiores às margens do Jordão, e um deles perde o machado emprestado, que cai n''água e afunda.', 'Diante do desespero do homem por não poder pagar algo que não era seu, Eliseu joga um pedaço de pau na água, e o ferro pesado sobe à superfície, flutuando o suficiente para ser recuperado.', 'Nenhum problema é pequeno demais para merecer atenção, mesmo quando comparado a crises maiores que também existem ao redor.', 'Mateus 10:29-31 traz o mesmo cuidado com detalhes pequenos: nem um pardal cai sem que seja notado.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ela preparou um quarto pra hospedar o profeta sem pedir nada em troca — e quando o filho que ganhou de presente morreu, se recusou a aceitar qualquer resposta que não fosse a vida dele de volta.', 'filho-da-sunamita', '2 Reis 4:8-37', 'Uma mulher rica de Suném prepara regularmente um quarto para hospedar Eliseu em suas viagens, sem pedir nada em troca, até o profeta insistir em abençoá-la com um filho, apesar de seu marido já ser idoso.', 'Anos depois, o menino morre subitamente. A mulher, sem contar a ninguém, vai direto atrás de Eliseu e se recusa a ser dispensada com respostas superficiais até ele mesmo vir restaurar a vida do filho.', 'Recusar-se a aceitar uma resposta menor do que a esperada, quando algo realmente importa, não é teimosia — pode ser exatamente o tipo de insistência que move a situação.', 'Lucas 18:1-8 ensina a mesma persistência através da parábola da viúva insistente diante do juiz.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Avisado de que ia morrer em breve, ele chorou, orou virado pra parede, e recebeu de resposta mais quinze anos de vida.', 'ezequias-pediu-mais-tempo', '2 Reis 20:1-11', 'O rei Ezequias adoece gravemente, e o profeta Isaías lhe anuncia que não sobreviveria — uma sentença aparentemente final, entregue diretamente por um profeta confiável.', 'Ezequias se vira para a parede e chora, lembrando a Deus sua fidelidade. Antes mesmo de Isaías sair do palácio, a palavra muda: Deus concede quinze anos adicionais de vida, com um sinal confirmando a promessa.', 'Uma sentença ouvida, mesmo vinda de fonte confiável, ainda pode ser levada em oração honesta antes de ser aceita como palavra final.', 'Tiago 5:16 confirma esse tipo de oração: "a súplica de um justo pode muito em seus efeitos".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Durante uma reforma no templo, alguém encontrou um livro tão esquecido que ninguém mais sabia o que dizia — e quando foi lido em voz alta, o rei rasgou as próprias vestes.', 'josias-encontrou-o-livro', '2 Reis 22-23', 'Josias se torna rei ainda criança, numa época em que o templo estava deteriorado e a lei de Moisés praticamente esquecida por gerações de negligência religiosa.', 'Durante um reparo estrutural no templo, o sumo sacerdote encontra o "livro da lei" perdido havia tempos. Ao ouvi-lo lido, Josias rasga suas vestes em choque, percebendo o quanto o povo tinha se afastado do que estava escrito, e inicia uma reforma completa.', 'Redescobrir algo que sempre esteve disponível, mas foi esquecido por negligência, pode ser tão transformador quanto uma revelação totalmente nova.', '2 Timóteo 3:16-17 fala do mesmo valor permanente da Escritura, útil mesmo depois de gerações de esquecimento.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um homem quase não mencionado em toda a Bíblia pediu, numa única oração curta, para ser abençoado além dos próprios limites — e recebeu exatamente isso.', 'oracao-de-jabes', '1 Crônicas 4:9-10', 'Jabes aparece só nesses dois versículos em meio a longas genealogias, descrito como "mais ilustre do que seus irmãos", cuja mãe deu esse nome porque o teve com dor.', 'Sua oração pede bênção, território ampliado, a presença de Deus e proteção contra o mal, "para que não me cause dor". O texto conclui secamente: "Deus lhe concedeu o que pediu".', 'Uma vida quase invisível na história ainda pode conter uma oração ousada o suficiente para mudar seu próprio curso.', 'Tiago 4:2 lembra o oposto: "não tendes, porque não pedis" — Jabes pediu, especificamente e sem timidez.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Antes de pedir qualquer coisa ao rei mais poderoso do mundo conhecido, ele passou meses chorando e orando em particular pela cidade destruída que amava.', 'neemias-orou-antes-de-pedir', 'Neemias 1', 'Neemias, copeiro do rei persa, recebe notícias de que os muros de Jerusalém continuam destruídos décadas depois do retorno do exílio, deixando a cidade vulnerável e humilhada.', 'Ele chora, jejua e ora por dias antes de tomar qualquer atitude prática, reconhecendo o pecado do povo e apelando às promessas antigas de Deus, só depois reunindo coragem para pedir ao rei permissão para agir.', 'Antes de agir sobre algo que dói profundamente, existe valor em processar essa dor em oração honesta, mesmo que isso pareça atrasar a ação prática.', 'Filipenses 4:6 recomenda a mesma ordem: oração e súplica antes, ação depois.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Uma árvore plantada perto de água constante não precisa se esforçar pra florescer na estação certa — ela só precisa estar enraizada no lugar certo.', 'arvore-junto-a-riachos', 'Salmos 1', 'O primeiro salmo funciona como introdução ao livro inteiro, contrastando duas trajetórias de vida possíveis: a de quem se enraíza em sabedoria e a de quem segue o conselho de quem não tem direção nenhuma.', 'A pessoa descrita como abençoada é comparada a uma árvore plantada junto a ribeiros de águas, que dá fruto no tempo certo e cuja folha não cai — resultado de onde as raízes estão fincadas, não de esforço visível na copa.', 'Frutificação constante geralmente é sinal de raiz bem posicionada, não de esforço frenético nos galhos.', 'Jeremias 17:7-8 retoma exatamente a mesma imagem, décadas depois, com quase as mesmas palavras.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Descrito como quem "habita no esconderijo do Altíssimo", o salmo promete proteção não pela ausência do perigo, mas por estar debaixo da sombra certa em meio a ele.', 'abrigo-do-altissimo', 'Salmos 91', 'O Salmo 91 é um dos textos de proteção mais citados da Bíblia, estruturado como uma declaração de confiança sobre morar sob a proteção divina em meio a perigos reais — pestilência, guerra, ataques noturnos.', 'A imagem central é abrigo: asas, sombra, fortaleza. O salmo não promete ausência de perigo ao redor, promete um lugar seguro dentro dele, "debaixo das suas asas te confiarás".', 'Segurança, nesse salmo, não é sobre o perigo desaparecer — é sobre onde você escolhe se abrigar enquanto ele está por perto.', 'Mateus 23:37 usa a mesma imagem de asas protetoras, agora vindo da própria boca de Jesus sobre Jerusalém.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A pergunta começa olhando pra cima, pros montes, buscando de onde viria o socorro — e a resposta vem imediata: não dos montes, de quem os fez.', 'elevo-os-olhos-para-os-montes', 'Salmos 121', 'Este salmo faz parte de uma coleção conhecida como "cânticos de romagem", provavelmente cantados por peregrinos subindo a Jerusalém, muitas vezes por caminhos montanhosos e perigosos.', '"Elevo os meus olhos para os montes; de onde vem o meu socorro?" O salmo responde de forma direta: o socorro vem do Senhor, que não dorme nem cochila, guardando a entrada e a saída de quem confia nele.', 'Buscar ajuda olhando na direção certa importa mais do que a intensidade da busca — nem todo lugar que parece imponente é de onde vem o socorro real.', 'Salmos 46:1 confirma a mesma fonte: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Sedento como um cervo procurando água num terreno seco, o autor confessa que sua alma tem sede de Deus em meio às próprias lágrimas dia e noite.', 'como-a-corca-anseia', 'Salmos 42', 'Este salmo é atribuído aos coraítas, escrito num momento de exílio ou afastamento do templo, misturando saudade espiritual com angústia emocional aberta.', '"Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus." O salmista chora dia e noite, questiona a própria alma sobre o abatimento, e se repreende a esperar em Deus mesmo sem sentir alívio imediato.', 'Sede espiritual genuína pode coexistir com lágrimas constantes — a proximidade de Deus não elimina automaticamente a dor presente.', 'João 7:37 traz a mesma linguagem de sede: "se alguém tem sede, venha a mim e beba".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um convite curto e direto: entre com alegria, cante, saiba que ele é Deus, e agradeça — sem complicação nenhuma no meio do caminho.', 'entrai-com-accao-de-gracas', 'Salmos 100', 'É um dos salmos mais curtos e diretos de louvor comunitário, provavelmente cantado em procissão na entrada do templo, sem nenhum lamento ou pedido — só celebração.', '"Entrai por suas portas com ação de graças, e nos seus átrios com louvor." O salmo lembra que Deus é quem fez o povo, não o contrário, e que sua bondade e fidelidade se estendem por gerações.', 'Nem toda aproximação de Deus precisa começar por um pedido ou um lamento. Às vezes o ponto de partida certo é só gratidão simples.', '1 Tessalonicenses 5:18 pede a mesma prática cotidiana: "em tudo dai graças".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('"O coração alegre é um bom remédio", diz o texto — colocando disposição emocional lado a lado com saúde física, não como assuntos separados.', 'coracao-alegre-bom-remedio', 'Provérbios 17:22', 'Está numa sequência de provérbios sobre disposição, relacionamentos e caráter, comparando estados emocionais aos seus efeitos práticos no corpo e na vida.', '"O coração alegre serve de bom remédio, mas o espírito abatido seca os ossos." A comparação é direta: alegria tem efeito medicinal, tristeza prolongada tem efeito de desgaste físico real.', 'Cuidar do próprio ânimo não é luxo nem frescura — tem efeito concreto sobre disposição, saúde e capacidade de atravessar dificuldades.', 'Provérbios 15:13 reforça: "o coração alegre aformoseia o rosto, mas pela dor do coração o espírito se abate".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('"Instrui a criança no caminho em que deve andar" — não promete resultado instantâneo, promete que o que é plantado cedo tende a permanecer.', 'instrui-a-crianca', 'Provérbios 22:6', 'Parte de uma seção de Provérbios voltada a formação de caráter e educação, num contexto onde a criação dos filhos era responsabilidade direta e cotidiana da família, não delegada a instituições.', '"Instrui a criança no caminho em que deve andar, e até quando envelhecer não se desviará dele." O verbo sugere direção contínua, não uma única lição — formação como processo, não evento.', 'O que é ensinado com constância na infância tende a deixar uma marca duradoura, mesmo que o efeito completo só apareça décadas depois.', '2 Timóteo 1:5 mostra esse princípio funcionando: a fé sincera de Timóteo, herdada primeiro da avó e da mãe.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Descrito séculos antes como alguém desprezado, rejeitado, que carregaria as dores de outros sem abrir a boca em defesa própria — um retrato que intriga leitores até hoje.', 'o-servo-sofredor', 'Isaías 53', 'Isaías escreve sobre uma figura chamada "servo sofredor", num dos textos proféticos mais debatidos e citados de todo o Antigo Testamento, escrito séculos antes de qualquer evento que os cristãos associam a ele.', 'O servo é descrito como "desprezado e rejeitado", "traspassado pelas nossas transgressões", carregando dor que não era originalmente sua, e ainda assim silencioso diante da injustiça, "como a ovelha muda perante os seus tosquiadores".', 'Sofrimento que carrega peso de outros, aceito sem retaliação, é apresentado aqui não como fraqueza, mas como o tipo mais alto de força.', 'Atos 8:32-35 mostra o eunuco etíope lendo justamente essa passagem quando Filipe se aproxima para explicá-la.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Escrita para um povo exilado, longe de casa, sem previsão de volta, a promessa não era de resgate imediato — era de que o plano continuava sendo bom, mesmo dali.', 'planos-de-paz-e-nao-de-mal', 'Jeremias 29:11', 'Jeremias escreve essa carta aos judeus recém-exilados na Babilônia, que esperavam uma libertação rápida — e a instrução, surpreendentemente, é para se estabelecerem ali, construírem casas e buscarem o bem-estar da cidade estrangeira.', '"Porque eu bem sei os pensamentos que penso de vós [...] pensamentos de paz, e não de mal, para vos dar o fim que esperais." A promessa vem junto de uma instrução de setenta anos de espera, não de alívio instantâneo.', 'Um plano bom nem sempre significa resgate imediato — às vezes significa propósito e sentido mesmo dentro do tempo de espera que ainda falta atravessar.', 'Romanos 8:28 generaliza essa mesma confiança: tudo cooperando para o bem, mesmo sem prazo definido.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Em vez de mais uma lei escrita em pedra, a promessa era de algo escrito por dentro — um coração novo que não precisaria mais ser lembrado de fora pra obedecer.', 'coracao-novo-alianca-nova', 'Jeremias 31:31-34', 'Jeremias profetiza durante um dos períodos mais sombrios de Judá, prestes ao exílio babilônico, anunciando não apenas restauração física, mas uma mudança interna prometida para o futuro.', '"Porei a minha lei no seu interior, e a escreverei no seu coração [...] e não mais ensinará cada um a seu próximo [...] porque todos me conhecerão." A nova aliança prometida não depende mais de tábuas externas.', 'Mudança duradoura raramente vem só de regras impostas de fora — vem quando o próprio desejo interno muda de direção.', 'Hebreus 8:10-12 cita essa profecia inteira para explicar o que Jesus estabelece como cumprimento dela.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Estrangeiros que estudavam o céu viram um sinal e viajaram meses atrás dele, enquanto quem morava a poucos quilômetros do nascimento nem percebeu que algo tinha acontecido.', 'magos-seguiram-a-estrela', 'Mateus 2:1-12', 'Magos do Oriente — provavelmente astrônomos ou sábios estrangeiros, não necessariamente reis — observam um fenômeno celeste e o interpretam como sinal do nascimento de um rei judeu, viajando uma longa distância para encontrá-lo.', 'Eles passam primeiro por Jerusalém, perguntando à corte de Herodes, que se perturba com a notícia. Guiados novamente pela estrela, chegam a Belém, adoram o menino e oferecem ouro, incenso e mirra, antes de voltar por outro caminho, avisados em sonho a evitar Herodes.', 'Reconhecer algo significativo às vezes exige vir de longe, prestar atenção a sinais sutis, e estar disposto a seguir uma direção que ninguém mais ao redor está seguindo.', 'Números 24:17 já falava séculos antes de uma estrela que sairia de Jacó — uma profecia que os magos parecem ter conhecido.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Vestido de peles, comendo gafanhotos no deserto, ele atraía multidões pregando arrependimento — e quando o próprio Jesus veio até ele, disse que não era digno nem de servi-lo.', 'joao-batista-preparava-o-caminho', 'Mateus 3:1-12', 'João Batista aparece pregando no deserto da Judeia, vivendo de forma austera, chamando as pessoas ao arrependimento e batizando no rio Jordão como sinal de mudança de vida antes da chegada do Messias.', 'Quando confrontado por líderes religiosos, João nega ser o Messias e se descreve apenas como "voz do que clama no deserto", preparando caminho. Ao ver Jesus se aproximar para ser batizado, ele tenta impedir, dizendo que era ele quem precisava ser batizado por Jesus.', 'Preparar o caminho para algo maior do que você mesmo, sem tentar ocupar o centro dele, é uma forma rara e valiosa de missão.', 'João 3:30 resume a postura de João Batista numa frase: "convém que ele cresça e que eu diminua".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Quando pediram pra ele ensinar a orar, a resposta não foi uma fórmula complicada — foi uma oração curta o bastante pra ser decorada em minutos e profunda o bastante pra levar uma vida inteira.', 'pai-nosso', 'Mateus 6:9-13', 'No Sermão do Monte, Jesus ensina essa oração como modelo, logo depois de criticar orações longas e performáticas feitas para impressionar quem está assistindo.', 'A oração começa reconhecendo a santidade de Deus, pede que Sua vontade seja feita, depois pede provisão diária, perdão condicionado ao próprio perdão oferecido a outros, e proteção contra a tentação — nessa ordem específica.', 'Uma oração não precisa ser longa ou elaborada para ser completa. Essa cobre adoração, necessidade, relacionamento e proteção em poucas linhas.', 'Lucas 11:1-4 traz a mesma oração numa versão ligeiramente diferente, ensinada quando os discípulos pedem diretamente para aprender a orar.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Antes de tirar o cisco do olho do outro, a instrução foi olhar pra trave no próprio — uma imagem exagerada de propósito, pra deixar claro o tamanho da hipocrisia comum.', 'trave-no-proprio-olho', 'Mateus 7:1-5', 'Ainda no Sermão do Monte, Jesus fala sobre julgamento entre pessoas, usando uma imagem visual exagerada e quase cômica para ilustrar um ponto sério sobre autocrítica antes da crítica alheia.', '"Por que reparas tu no argueiro que está no olho do teu irmão, e não vês a trave que está no teu?" A instrução não proíbe ajudar o outro a enxergar melhor — proíbe fazer isso sem antes examinar a própria visão distorcida.', 'Antes de apontar o defeito de alguém com convicção, vale medir a própria régua pelo mesmo padrão que está sendo aplicado ao outro.', 'Romanos 2:1 traz a mesma advertência em tom mais direto, sobre quem julga praticando coisas parecidas.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Duas casas, construídas de formas parecidas, só se diferenciam quando a tempestade chega — uma cai, a outra não, e a diferença estava toda na fundação escondida.', 'casa-sobre-a-rocha', 'Mateus 7:24-27', 'Jesus encerra o Sermão do Monte com essa parábola, comparando quem ouve seus ensinamentos e os pratica com quem apenas ouve sem aplicar nada na prática.', 'As duas casas parecem idênticas por fora até a tempestade — chuva, enchente, vento — expor a diferença real: uma foi construída sobre rocha, a outra sobre areia, e só a segunda desaba completamente.', 'A qualidade de uma fundação normalmente só fica visível sob pressão. Antes da tempestade, casa sobre rocha e casa sobre areia parecem exatamente iguais.', '1 Coríntios 3:11 usa a mesma imagem de fundação, agora explicitamente identificando Cristo como a única base que resiste.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Dez esperavam o mesmo noivo com a mesma lâmpada acesa — só que cinco levaram azeite reserva e cinco não, e quando ele demorou, essa diferença decidiu quem entrou na festa.', 'dez-virgens-e-o-azeite', 'Mateus 25:1-13', 'Jesus conta essa parábola pouco antes de sua crucificação, num bloco de ensino sobre estar preparado para um retorno cuja hora exata ninguém sabe.', 'Dez damas de honra esperam um noivo que demora mais que o previsto. Cinco levaram azeite extra para as lâmpadas, cinco não. Quando o noivo finalmente chega à meia-noite, as sem azeite saem correndo comprar mais, e voltam tarde demais, encontrando a porta já fechada.', 'Preparo de longo prazo não pode ser improvisado no último minuto quando a espera se estende mais do que se esperava.', '1 Pedro 4:7 pede a mesma vigilância: "o fim de todas as coisas está próximo; sede, pois, sóbrios".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('No julgamento final descrito, a pergunta decisiva não era sobre doutrina ou discurso — era se alguém tinha dado comida a quem tinha fome e visitado quem estava preso.', 'ovelhas-e-cabritos', 'Mateus 25:31-46', 'Jesus descreve uma cena de julgamento futuro, separando pessoas como um pastor separa ovelhas de cabritos, pouco antes de sua própria prisão e crucificação.', 'O critério de separação é surpreendentemente concreto: dar comida a quem tem fome, água a quem tem sede, roupa a quem está nu, visitar doentes e presos. Jesus se identifica diretamente com quem sofre: "quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes".', 'Cuidado prático com quem está em necessidade concreta não é um detalhe secundário da fé — no texto, é o próprio critério central de avaliação.', 'Tiago 2:15-16 traz a mesma cobrança: fé que vê necessidade real e só oferece boas palavras, sem ação, não vale nada.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A última instrução antes de partir não foi um plano detalhado — foi uma ordem ampla, seguida da promessa de companhia constante até o fim de tudo.', 'ide-fazei-discipulos', 'Mateus 28:16-20', 'Depois da ressurreição, Jesus se encontra com os onze discípulos num monte na Galileia, num dos últimos momentos registrados antes de sua ascensão.', '"Toda a autoridade me foi dada [...] portanto ide, fazei discípulos de todas as nações [...] e eis que eu estou convosco todos os dias, até a consumação dos séculos." A missão é ampla, mas vem junto de uma promessa de presença constante, não de abandono.', 'Uma missão grande demais para cumprir sozinho vem, nesse texto, sempre acompanhada da promessa de não ser cumprida sozinho.', 'Atos 1:8 detalha o alcance geográfico dessa mesma missão: começando perto, se espalhando até os confins da terra.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Enquanto ricos depositavam grandes somas visivelmente, uma viúva colocou duas moedinhas de pouquíssimo valor — e foi ela quem Jesus apontou como quem mais tinha dado.', 'duas-moedinhas-da-viuva', 'Marcos 12:41-44', 'Jesus observa pessoas depositando ofertas no templo, num contexto onde doações eram muitas vezes feitas de forma visível e ostensiva por quem tinha recursos.', 'Uma viúva pobre deposita duas pequenas moedas, valor quase insignificante. Jesus chama os discípulos e declara que ela deu mais do que todos os outros, porque os outros deram do que sobrava, e ela deu tudo que tinha para viver.', 'O valor real de uma oferta, de tempo ou de esforço, não se mede pelo tamanho absoluto, mas pela proporção do que custou a quem deu.', '2 Coríntios 8:12 confirma o mesmo princípio: a boa vontade é aceita de acordo com o que se tem, não com o que não se tem.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Mandaram ele ficar quieto, mas quanto mais tentavam calá-lo, mais alto ele gritava — e foi esse grito insistente que fez Jesus parar no meio da multidão.', 'bartimeu-gritou-mais-alto', 'Marcos 10:46-52', 'Bartimeu, um mendigo cego, está sentado à beira do caminho em Jericó quando ouve que Jesus está passando com uma grande multidão.', 'Ele começa a gritar pedindo misericórdia, e várias pessoas tentam silenciá-lo. Em vez de se calar, ele grita ainda mais alto, até Jesus parar e mandar chamá-lo. Bartimeu joga fora sua capa — provavelmente sua única proteção contra o frio — e corre até ele.', 'Pedir ajuda com insistência, mesmo quando as pessoas ao redor tentam te silenciar, às vezes é exatamente o que faz alguém parar e prestar atenção.', 'Lucas 18:1 ensina o mesmo princípio de forma direta: orar sempre, sem desanimar.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ele fez tudo certo a vida inteira, guardou todos os mandamentos desde jovem, e ainda assim foi embora triste quando pediram a única coisa que ele não queria soltar.', 'jovem-rico-foi-embora-triste', 'Marcos 10:17-22', 'Um homem rico e cumpridor da lei religiosa se aproxima de Jesus perguntando o que precisa fazer para herdar a vida eterna, genuinamente interessado, não testando por má-fé.', 'Jesus lista os mandamentos, e o homem responde que já guardava todos desde jovem. Jesus, olhando para ele com amor segundo o texto, pede uma última coisa: vender tudo que tinha e dar aos pobres. O homem se entristece e vai embora, porque tinha muitas posses.', 'Cumprir regras corretamente não impede que exista um ponto específico de apego que ainda precisa ser confrontado diretamente.', 'Lucas 19:1-10 mostra o contraste: Zaqueu, outro homem rico, oferece voluntariamente metade dos bens sem nem ser pedido.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Grávida, ainda adolescente, numa situação socialmente arriscada, ela respondeu com um cântico sobre um Deus que derruba poderosos e exalta os humildes.', 'magnificat-de-maria', 'Lucas 1:46-55', 'Maria, recém-anunciada como mãe do Messias, visita sua parenta Isabel, também grávida milagrosamente, e responde à saudação com um cântico de louvor conhecido como Magnificat.', '"A minha alma engrandece ao Senhor [...] derribou dos tronos os poderosos, e elevou os humildes; encheu de bens os famintos, e despediu vazios os ricos." É um cântico de inversão radical, vindo de alguém socialmente vulnerável.', 'A perspectiva de quem está em posição frágil sobre o que Deus está fazendo pode ser mais aguda do que a de quem observa de uma posição confortável.', '1 Samuel 2:1-10 traz um cântico quase idêntico em tema, de Ana, também numa posição social vulnerável antes de receber Samuel.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um sacerdote e um levita passaram direto pelo homem ferido na estrada — foi um estrangeiro de um povo desprezado quem parou, cuidou e pagou pela recuperação dele.', 'bom-samaritano', 'Lucas 10:25-37', 'Um especialista na lei pergunta a Jesus quem é seu próximo, tentando justificar os próprios limites de compaixão. Jesus responde com uma parábola em vez de uma definição.', 'Um homem é espancado e deixado quase morto na estrada. Um sacerdote e um levita — figuras religiosas respeitadas — passam pelo outro lado. Um samaritano, de um povo desprezado pelos judeus da época, para, cuida dos ferimentos, e paga do próprio bolso pela recuperação completa dele numa hospedaria.', 'Proximidade real com alguém em necessidade não depende de categoria social, religiosa ou de quem "deveria" ajudar por obrigação — depende de quem realmente para.', 'Tiago 2:15-17 reforça: fé genuína se prova em cuidado concreto, não em discurso sobre quem merece ajuda.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ela voltava repetidamente pedindo justiça a um juiz que não temia a Deus nem se importava com ninguém — e foi só de tanto insistir que ele finalmente cedeu.', 'viuva-insistente', 'Lucas 18:1-8', 'Jesus conta essa parábola especificamente, segundo o texto, "para mostrar que era necessário orar sempre, e nunca desfalecer".', 'Uma viúva sem recursos nem influência continua voltando ao mesmo juiz injusto pedindo justiça contra seu adversário. Ele a ignora por um tempo, mas cede só porque ela não para de incomodá-lo — não por bondade própria, mas por cansaço.', 'Se até um juiz sem nenhuma compaixão cede à persistência, a comparação implícita é: quanto mais alguém que se importa de verdade responderia à persistência sincera.', 'Lucas 11:5-8 traz uma parábola parecida sobre pedir pão a um amigo à meia-noite, com a mesma lógica de insistência recompensada.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um orava listando as próprias virtudes em voz alta; o outro nem levantava os olhos, só batia no peito pedindo misericórdia — e foi o segundo que saiu justificado.', 'fariseu-e-o-publicano', 'Lucas 18:9-14', 'Jesus conta essa parábola para pessoas que confiavam na própria justiça e desprezavam os outros, contrastando duas orações feitas ao mesmo tempo no templo.', 'O fariseu agradece a Deus por não ser como os outros pecadores, listando seus próprios méritos religiosos. O publicano, cobrador de impostos desprezado socialmente, nem ousa levantar os olhos, batendo no peito e pedindo: "Deus, tem misericórdia de mim, pecador". Jesus diz que foi este último quem voltou justificado para casa.', 'Reconhecer a própria necessidade, sem comparação com ninguém mais, costuma abrir mais espaço para graça do que qualquer lista de méritos próprios.', 'Tiago 4:6 confirma a mesma inversão: "Deus resiste aos soberbos, mas dá graça aos humildes".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Antes de qualquer coisa existir, a Palavra já estava lá — e o texto descreve o momento em que essa Palavra eterna se tornou alguém que podia ser visto, tocado e conhecido de perto.', 'o-verbo-se-fez-carne', 'João 1:1-14', 'O Evangelho de João abre de forma diferente dos outros três, sem genealogia nem relato de nascimento, começando num tom quase idêntico ao início de Gênesis: "no princípio".', '"No princípio era o Verbo [...] e o Verbo era Deus [...] E o Verbo se fez carne, e habitou entre nós." O texto identifica Jesus como a própria expressão eterna de Deus, agora tornada visível e próxima.', 'A ideia de um Deus distante e abstrato é substituída aqui por algo que escolheu se tornar próximo, tangível, presente entre pessoas comuns.', 'Colossenses 1:15 chama Jesus de "a imagem do Deus invisível" — o mesmo movimento de tornar visível o que era abstrato.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Numa festa de casamento comum, quando o vinho acabou, seis potes de água usados para purificação viraram o melhor vinho da celebração — o primeiro sinal público, guardado para o fim.', 'agua-em-vinho-em-cana', 'João 2:1-11', 'Jesus e seus discípulos, junto com sua mãe Maria, participam de um casamento em Caná da Galileia quando o vinho da festa acaba, uma falha social embaraçosa para os anfitriões.', 'Maria avisa Jesus da falta, e ele manda encher seis potes de pedra, usados para purificação ritual, com água — que se torna vinho de qualidade superior ao servido antes. O texto chama isso de "princípio dos sinais" de Jesus.', 'Transformação genuína às vezes acontece em algo tão comum quanto potes usados para lavagem, não apenas em cenários dramáticos.', 'João 4:46 volta à mesma cidade de Caná para outro milagre, ligando os dois episódios pela mesma geografia.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um líder religioso respeitado foi conversar com Jesus escondido, de noite, com medo do que os outros pensariam — e ouviu que precisava nascer de novo pra realmente entender.', 'nicodemos-nascer-de-novo', 'João 3:1-16', 'Nicodemos era fariseu e membro do Sinédrio, uma figura de autoridade religiosa reconhecida, que procura Jesus à noite — possivelmente para evitar ser visto associado a ele publicamente.', 'Jesus lhe diz que ninguém pode ver o Reino de Deus sem nascer de novo, o que confunde Nicodemos, que pergunta como alguém pode voltar ao ventre da mãe. Jesus esclarece que fala de um nascimento espiritual, não físico, e nesse contexto declara: "porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito".', 'Conhecimento religioso acumulado não substitui uma transformação interna real — os dois podem, inclusive, coexistir sem se tocar.', 'João 19:39 revela que esse mesmo Nicodemos, anos depois, ajuda abertamente a preparar o corpo de Jesus para o sepultamento — a busca noturna amadureceu em coragem pública.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ele se descreveu como o pastor que conhece cada ovelha pelo nome, e que — diferente de quem só trabalha por salário — estaria disposto a dar a própria vida por elas.', 'eu-sou-o-bom-pastor', 'João 10:1-18', 'Jesus fala essa imagem logo depois de curar um cego de nascença e enfrentar críticas de líderes religiosos, contrastando sua relação com o povo com a de "maus pastores" que exploram o rebanho.', '"Eu sou o bom pastor; o bom pastor dá a sua vida pelas ovelhas [...] conheço as minhas ovelhas, e das minhas sou conhecido." Diferente do mercenário que foge quando o lobo aparece, o bom pastor permanece mesmo em risco pessoal.', 'Existe diferença entre quem cuida por obrigação temporária e quem se compromete de verdade, mesmo quando isso custa caro.', 'Salmos 23 já tinha estabelecido séculos antes essa mesma imagem pastoral de cuidado próximo e pessoal.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ele se comparou a uma videira e disse que sem estar ligado a ela, ninguém consegue produzir fruto nenhum — a força não vem do galho, vem da raiz.', 'videira-verdadeira', 'João 15:1-8', 'Na última noite antes de sua prisão, durante a última ceia, Jesus usa a imagem de uma videira para explicar aos discípulos como sua relação com eles deveria continuar depois que ele partisse.', '"Eu sou a videira, vós as varas [...] separados de mim, nada podereis fazer." Ramos que não permanecem ligados à videira secam e são cortados; os que permanecem, e são podados, produzem mais fruto.', 'Esforço desconectado da fonte certa tende a se esgotar. Produtividade sustentável depende de permanência, não só de esforço isolado.', 'Gálatas 5:22-23 descreve exatamente o tipo de fruto que cresce dessa conexão: amor, alegria, paz, paciência.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Quando disseram que ele nem tinha idade suficiente para ter visto Abraão, a resposta usou o mesmo nome que Deus tinha usado séculos antes na sarça ardente.', 'antes-de-abraao-eu-sou', 'João 8:56-59', 'Jesus está em debate acalorado com líderes religiosos no templo, que questionam sua autoridade e ascendência, comparando-o desfavoravelmente com Abraão.', 'Jesus declara que Abraão se alegrou por ver o dia dele. Os líderes zombam, dizendo que ele ainda não tinha nem cinquenta anos para ter visto Abraão. Jesus responde: "antes que Abraão existisse, eu sou" — usando a mesma expressão que Deus usa em Êxodo 3:14, o que quase leva à sua execução imediata por apedrejamento.', 'Algumas declarações não deixam espaço para meio-termo — ou são absurdas ou mudam completamente como você entende quem as fez.', 'Êxodo 3:14 é a origem dessa expressão: "Eu Sou o que Sou", o próprio nome que Deus revela a Moisés na sarça.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Enquanto era apedrejado até a morte por dizer a verdade, ele orou pedindo que aquele pecado não fosse cobrado de quem o estava matando — e morreu em paz.', 'estevao-perdoou-ao-morrer', 'Atos 7:54-60', 'Estêvão, um dos primeiros diáconos da igreja, é levado ao Sinédrio acusado de blasfêmia depois de um discurso corajoso resumindo toda a história de Israel e confrontando diretamente seus acusadores.', 'Enfurecidos, os líderes o arrastam para fora da cidade e o apedrejam. Enquanto morre, Estêvão vê os céus abertos, ora pedindo que Deus receba seu espírito, e depois se ajoelha pedindo que esse pecado não seja cobrado dos que o matavam — morrendo com essa oração de perdão nos lábios.', 'Perdão oferecido no próprio momento de maior injustiça sofrida é o tipo mais radical de perdão descrito na Bíblia — e ainda assim é apresentado como possível.', 'Lucas 23:34 mostra Jesus fazendo exatamente a mesma oração na cruz: "Pai, perdoa-lhes, porque não sabem o que fazem".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um estrangeiro poderoso lia um profeta antigo sem entender nada, sozinho numa estrada deserta — até um desconhecido aparecer do nada pra explicar exatamente aquele trecho.', 'eunuco-etiope-no-deserto', 'Atos 8:26-39', 'Filipe é guiado por um anjo a uma estrada deserta entre Jerusalém e Gaza, onde encontra um alto funcionário etíope, eunuco da corte da rainha Candace, voltando de uma peregrinação, lendo o livro de Isaías em seu carro.', 'O eunuco lia justamente a passagem sobre o servo sofredor, sem entender do que se tratava. Filipe se aproxima, explica que o texto fala de Jesus, e o eunuco pede para ser batizado ali mesmo, assim que veem água na estrada.', 'Entendimento genuíno de um texto difícil às vezes só chega quando alguém disposto a explicar aparece exatamente no momento certo, mesmo num lugar improvável.', 'Isaías 53 é justamente a passagem que o eunuco estava lendo — o mesmo servo sofredor que intriga leitores até hoje.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um oficial romano, gentio, temente a Deus mas fora da aliança judaica, recebeu uma visão pedindo que chamasse um pescador — e essa visita quebrou uma barreira que ninguém esperava ver quebrada.', 'visao-de-cornelio', 'Atos 10', 'Cornélio, centurião romano, é descrito como piedoso e generoso, mas gentio — fora da aliança formal com Israel. Ele recebe uma visão instruindo-o a chamar Pedro, enquanto Pedro, separadamente, recebe uma visão preparando-o para aceitar o convite.', 'Pedro, que tinha crescido evitando contato com gentios por convicção religiosa, entende através da visão que não deveria mais chamar de impuro o que Deus tinha purificado. Ele vai até a casa de Cornélio, prega, e o Espírito Santo desce sobre os presentes antes mesmo do batismo formal.', 'Convicções antigas e bem estabelecidas, mesmo religiosas, às vezes precisam ser revisitadas quando confrontadas com uma verdade maior que estava sendo negligenciada.', 'Gálatas 3:28 declara o resultado teológico dessa quebra de barreira: "não há judeu nem grego [...] porque todos vós sois um em Cristo Jesus".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Uma comerciante de púrpura, já temente a Deus, estava simplesmente orando à beira de um rio quando ouviu Paulo pregar — e o texto diz que foi o Senhor quem abriu o coração dela pra prestar atenção.', 'lidia-abriu-o-coracao', 'Atos 16:11-15', 'Paulo chega a Filipos, cidade sem sinagoga formal, e encontra um pequeno grupo de mulheres orando à beira de um rio num sábado, entre elas Lídia, comerciante de tecidos púrpura, vinda de Tiatira.', '"O Senhor lhe abriu o coração para que atendesse às coisas que Paulo dizia." Lídia se converte, é batizada com toda sua casa, e insiste hospitaleiramente para que Paulo e seus companheiros fiquem em sua casa.', 'Receptividade genuína a uma mensagem importante muitas vezes é descrita não como esforço próprio, mas como algo que acontece por dentro, além do controle da própria vontade.', 'Lucas 24:45 descreve o mesmo tipo de abertura: Jesus abrindo o entendimento dos discípulos para compreender as Escrituras.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Depois de listar tribulação, angústia, perseguição, fome, perigo e espada, a conclusão não foi de derrota — foi que nada disso, nem morte nem vida, seria capaz de separar de um amor específico.', 'nada-pode-nos-separar', 'Romanos 8:31-39', 'Paulo escreve aos romanos concluindo um dos argumentos teológicos mais densos do Novo Testamento sobre segurança e identidade em Cristo, culminando numa das passagens mais citadas em momentos de crise.', '"Quem nos separará do amor de Cristo? Será tribulação, ou angústia, ou perseguição [...] Porque estou certo de que nem a morte, nem a vida [...] nem alguma outra criatura nos poderá separar do amor de Deus."', 'A lista de coisas capazes de ameaçar essa segurança é extensa e realista — a promessa não ignora o sofrimento, ela afirma que nem o pior cenário imaginável quebra esse vínculo específico.', 'João 10:28-29 já tinha estabelecido a mesma segurança: "ninguém as arrebatará da minha mão".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A afirmação não separa as pessoas em categorias de mérito — todos erraram do mesmo jeito, e todos têm acesso à mesma graça gratuita, sem distinção alguma.', 'todos-pecaram-todos-justificados', 'Romanos 3:23-24', 'Paulo constrói, ao longo dos primeiros capítulos de Romanos, o argumento de que ninguém — nem judeu religioso nem gentio pagão — tem vantagem moral natural diante de Deus.', '"Todos pecaram e destituídos estão da glória de Deus, sendo justificados gratuitamente pela sua graça, mediante a redenção que há em Cristo Jesus." A igualdade aqui não é sobre o problema — é sobre a solução, oferecida sem distinção.', 'Comparar seu próprio erro com o erro de outra pessoa, tentando parecer melhor por comparação, perde sentido quando o ponto de partida real é o mesmo para todos.', 'Efésios 2:8-9 completa o pensamento: salvos pela graça, mediante a fé, "não vem de vós, é dom de Deus".', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um olho não pode dizer à mão "não preciso de ti" — cada parte, mesmo a que parece menos importante, é necessária pro corpo inteiro funcionar direito.', 'um-corpo-muitos-membros', '1 Coríntios 12:12-27', 'Paulo escreve à igreja de Corinto, dividida por comparações de status e dons espirituais, alguns membros se sentindo superiores por causa de habilidades mais visíveis.', 'Ele compara a igreja a um corpo humano: se todo o corpo fosse olho, onde estaria a audição? Cada parte, incluindo as que parecem mais fracas ou menos honrosas, recebe cuidado especial justamente por sua aparente fragilidade.', 'Sentir-se menos importante numa equipe ou comunidade não é indicador confiável do seu valor real dentro dela — o corpo inteiro depende de cada parte funcionando.', 'Romanos 12:4-5 traz a mesma imagem, reforçando que cada membro pertence uns aos outros, não funciona isolado.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A instrução final não foi sobre o que evitar, foi sobre onde direcionar a mente ativamente: tudo que é verdadeiro, honesto, justo, puro, amável, de boa fama.', 'pensai-nestas-coisas', 'Filipenses 4:8-9', 'Paulo escreve da prisão, perto do fim de uma carta marcada por alegria mesmo em circunstâncias difíceis, dando instruções práticas finais sobre como manter a paz mental.', '"Tudo o que é verdadeiro [...] justo [...] amável [...] de boa fama [...] se há alguma virtude, e se há algum louvor, nisso pensai." A instrução é ativa: escolher deliberadamente onde a mente se detém, não apenas evitar o negativo.', 'Saúde mental, nesse texto, não é só ausência de pensamento ruim — é escolha ativa e repetida de onde focar a atenção.', '2 Coríntios 10:5 fala da mesma disciplina mental: levar cativo todo pensamento à obediência de Cristo.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Três instruções curtas, encadeadas: alegrem-se sempre, orem sem cessar, deem graças em tudo — não em algumas circunstâncias específicas, em qualquer uma.', 'alegrai-vos-sempre', '1 Tessalonicenses 5:16-18', 'Paulo encerra sua primeira carta aos tessalonicenses com uma sequência rápida de instruções práticas para a vida cotidiana da igreja, sem muito desenvolvimento teórico entre elas.', '"Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco." As três instruções aparecem juntas, quase como um único hábito contínuo dividido em três expressões.', 'Essas três práticas — alegria, oração, gratidão — parecem mais sustentáveis quando tratadas como um hábito contínuo do que como reações pontuais a boas circunstâncias.', 'Filipenses 4:4 repete a mesma instrução de alegria constante, escrita da mesma prisão, nas mesmas circunstâncias difíceis.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Um rei teve um sonho perturbador e exigiu que os sábios não só o interpretassem, mas adivinhassem o próprio sonho sem ouvi-lo — e só um jovem cativo conseguiu.', 'daniel-interpreta-a-estatua', 'Daniel 2', 'Nabucodonosor, rei da Babilônia, tem um sonho perturbador e, desconfiado dos conselheiros, exige que eles revelem tanto o conteúdo do sonho quanto sua interpretação, sob pena de morte para todos os sábios do reino.', 'Daniel pede tempo, ora com os amigos, e recebe a revelação em visão noturna. Ele descreve uma estátua feita de diferentes metais, representando impérios sucessivos, destruída por uma pedra que se torna uma montanha — símbolo de um reino que nunca seria destruído.', 'Diante de uma exigência impossível, a resposta de Daniel não foi pânico nem improviso — foi buscar orientação antes de tentar responder sozinho.', 'Tiago 1:5 oferece a mesma saída para qualquer situação sem solução própria: pedir sabedoria a Deus.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('No meio de uma festa luxuosa, uma mão apareceu do nada e escreveu palavras estranhas na parede — e ninguém no salão conseguiu decifrar o aviso, exceto um homem já esquecido pela corte.', 'escrita-na-parede', 'Daniel 5', 'Belsazar, rei da Babilônia, organiza um banquete usando os utensílios sagrados roubados do templo de Jerusalém, um ato de profanação diante de mil convidados.', 'Uma mão aparece e escreve palavras misteriosas na parede. Nenhum sábio da corte consegue interpretar, até Daniel ser chamado e explicar que o reino tinha sido pesado na balança e achado em falta — naquela mesma noite, o rei morre e o reino cai.', 'Sinais de alerta às vezes aparecem de forma clara e visível, mas só quem tem discernimento certo consegue de fato interpretar o que está sendo dito.', 'Provérbios 16:18 resume o padrão: "antes da destruição vem a soberba", exatamente o que acontece nessa história.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Ele foi chamado de sentinela — não pra ser responsável pelo que os outros escolhessem fazer, mas pra ser responsável por avisar, o que era coisa bem diferente.', 'ezequiel-sentinela', 'Ezequiel 3:16-21', 'Deus chama Ezequiel para profetizar durante o exílio babilônico, atribuindo a ele a responsabilidade específica de avisar o povo, comparando essa função à de um sentinela numa muralha.', 'Se o sentinela vê o perigo chegando e não avisa, o sangue do povo cai sobre ele. Mas se ele avisa e o povo não escuta, o sentinela está livre da responsabilidade — o resultado final não depende mais dele.', 'Existe uma diferença clara entre a responsabilidade de avisar e a responsabilidade pelo resultado de quem ouve o aviso e decide não agir.', 'Atos 20:26-27 traz Paulo usando a mesma lógica: livre de culpa por ter anunciado tudo que precisava ser dito.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A promessa não era só de perdão — era de troca de material: um coração de pedra sendo removido e substituído por um de carne, capaz de sentir de novo.', 'coracao-de-carne', 'Ezequiel 36:26-27', 'Ezequiel profetiza restauração para um povo exilado que tinha, segundo o próprio texto, endurecido o coração ao longo de gerações de desobediência repetida.', '"Tirar-vos-ei o coração de pedra da vossa carne, e vos darei um coração de carne. E porei dentro de vós o meu Espírito." A mudança prometida não é apenas comportamental — é uma substituição interna completa.', 'Algumas mudanças de comportamento tentadas de fora para dentro não funcionam porque o problema real é um endurecimento mais profundo, que precisa ser tratado primeiro.', '2 Coríntios 3:3 fala da mesma transformação: uma carta escrita não em tábuas de pedra, mas em tábuas de carne do coração.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Deus mandou o profeta se casar com uma mulher que sabia que o trairia repetidamente — pra que sua própria vida virasse ilustração viva do que era amar alguém infiel.', 'oseias-e-gomer', 'Oseias 1-3', 'Oseias recebe uma instrução incomum: casar-se com Gômer, uma mulher com histórico de infidelidade, como sinal profético vivo da relação entre Deus e um povo que repetidamente se afastava para outros deuses.', 'Apesar das traições repetidas de Gômer, Deus instrui Oseias a buscá-la de volta e amá-la novamente, ilustrando um amor que persiste mesmo diante de infidelidade contínua — não como fraqueza, mas como escolha deliberada de restaurar.', 'Amor que persiste depois de traição repetida não é ingenuidade automaticamente — pode ser retrato de um tipo de compromisso que vai além do que a lógica comum recomendaria.', 'Romanos 5:8 traz a mesma lógica: "Deus prova o seu amor [...] sendo nós ainda pecadores", antes de qualquer mudança da nossa parte.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Deus disse que odiava as festas religiosas deles — não porque adoração fosse ruim, mas porque vinha misturada com injustiça que ninguém corrigia.', 'justica-como-agua-corrente', 'Amós 5:21-24', 'Amós profetiza numa época de prosperidade econômica em Israel, mas marcada por exploração dos pobres disfarçada por rituais religiosos elaborados e regulares.', '"Aborreço, desprezo as vossas festas [...] mas corra o juízo como as águas, e a justiça como ribeiro que não seca." Deus rejeita explicitamente adoração praticada sem justiça correspondente na vida prática.', 'Prática religiosa consistente não substitui justiça concreta nas relações e decisões do dia a dia — as duas precisam andar juntas.', 'Mateus 23:23 traz a mesma crítica de Jesus aos fariseus: cuidado com detalhes religiosos, negligenciando justiça, misericórdia e fé.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Depois de perguntar com que sacrifício grande poderia agradar a Deus, a resposta foi surpreendentemente simples: praticar a justiça, amar a misericórdia, andar humildemente.', 'o-que-o-senhor-pede', 'Miqueias 6:6-8', 'Miqueias responde a uma pergunta retórica sobre o que seria necessário para agradar a Deus — oferendas cada vez maiores, sacrifícios extremos — com uma resposta que rejeita essa lógica de troca.', '"Ele te declarou, ó homem, o que é bom [...] que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus." A resposta não é sobre quantidade de sacrifício, é sobre qualidade de caráter cotidiano.', 'A pergunta "o que mais eu preciso fazer" às vezes tem uma resposta mais simples e mais exigente ao mesmo tempo do que fazer mais coisas grandiosas.', '1 Samuel 15:22 já tinha estabelecido esse princípio: obedecer é melhor que sacrifício.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Mesmo descrevendo cenário de colheita zerada, fazenda vazia, nada nos currais, ele termina dizendo que ainda assim se alegraria no Senhor — sem trocar a alegria pela circunstância.', 'ainda-que-a-figueira-nao-floresca', 'Habacuque 3:17-19', 'Habacuque escreve depois de questionar Deus abertamente sobre injustiça e violência, recebendo respostas difíceis sobre um julgamento vindouro através de uma nação ainda mais violenta.', '"Ainda que a figueira não floresça [...] e os currais estejam sem gado, todavia eu me alegrarei no Senhor." A alegria descrita aqui não depende de nenhuma das evidências externas de provisão listadas.', 'Alegria genuína sustentada por convicção, não por circunstância, permite continuidade mesmo quando todos os indicadores externos apontam para escassez.', 'Filipenses 4:11-13 traz o mesmo tipo de contentamento aprendido independente das circunstâncias externas.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A imagem não é de um Deus distante avaliando de longe — é de alguém no meio do povo, se alegrando tanto a ponto de cantar de alegria por quem ele ama.', 'ele-se-alegra-com-cantos', 'Zefanias 3:17', 'Zefanias profetiza principalmente sobre julgamento, mas encerra o livro com uma das imagens mais ternas de toda a literatura profética sobre a proximidade de Deus.', '"O Senhor teu Deus está no meio de ti [...] ele se regozijará em ti com alegria, calar-se-á por seu amor, e se alegrará em ti com cânticos." A cena descrita é de intimidade e celebração, não de distância avaliativa.', 'A ideia de ser observado e avaliado à distância pode ser substituída pela imagem de ser motivo de alegria cantada por perto.', 'Lucas 15:22-24 traz a mesma celebração ativa: o pai organizando festa só porque o filho voltou.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Diante de uma tarefa que parecia impossível de completar com os recursos disponíveis, a resposta não foi sobre estratégia — foi que aconteceria "não por força, nem por violência, mas pelo meu Espírito".', 'nao-por-forca-nem-por-poder', 'Zacarias 4:6', 'Zacarias encoraja Zorobabel, líder responsável por reconstruir o templo depois do exílio, diante de recursos limitados e oposição externa significativa ao projeto.', '"Não por força nem por violência, mas pelo meu Espírito, diz o Senhor dos Exércitos." A promessa é que o que parecia um "grande monte" de obstáculo se tornaria uma planície diante de Zorobabel, por um meio diferente do esforço puramente humano.', 'Quando os recursos disponíveis claramente não bastam para o tamanho do desafio, isso pode ser exatamente o ponto em que outro tipo de força entra em ação.', '2 Coríntios 12:9 confirma o mesmo princípio: poder que se aperfeiçoa justamente na fraqueza, não na abundância de recursos.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A definição não foi "Deus tem amor" ou "Deus demonstra amor" — foi mais direta: "Deus é amor", como se os dois fossem, de alguma forma, a mesma coisa.', 'deus-e-amor', '1 João 4:7-8', 'João escreve numa comunidade enfrentando divisões e falsos ensinos, insistindo que amor genuíno entre os irmãos é evidência prática de conhecer Deus de verdade.', '"Aquele que não ama não conhece a Deus; porque Deus é amor." A afirmação não trata amor como um atributo entre outros, mas como definição central da própria natureza descrita.', 'Se a definição central é essa, então qualquer entendimento de Deus que exclua amor genuíno pelo próximo está, por definição, incompleto.', '1 Coríntios 13:4-7 detalha o que esse amor parece na prática: paciente, benigno, que tudo sofre, tudo espera.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('A instrução não foi pra parar de sentir ansiedade — foi pra lançar essa ansiedade em cima de alguém disposto a carregá-la, porque ele se importava de verdade.', 'lancai-sobre-ele-a-ansiedade', '1 Pedro 5:6-7', 'Pedro escreve a cristãos espalhados enfrentando perseguição e instabilidade, dando instruções práticas de humildade e confiança em meio a circunstâncias genuinamente ameaçadoras.', '"Humilhai-vos, pois, sob a potente mão de Deus [...] lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." A instrução conecta humildade com a ação prática de entregar preocupação a alguém confiável.', 'Ansiedade não precisa ser resolvida sozinha antes de ser entregue — o texto sugere entregá-la exatamente enquanto ainda pesa, não depois de já ter sido controlada.', 'Filipenses 4:6-7 detalha o mesmo processo: apresentar pedidos com ação de graças, e receber paz que excede todo entendimento em troca.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Cercados por uma "nuvem de testemunhas" que já tinham corrido antes, a instrução era despojar-se de todo peso desnecessário e correr com paciência, olhando fixamente para um único ponto à frente.', 'correi-com-perseveranca', 'Hebreus 12:1-2', 'Hebreus 12 vem logo depois do capítulo 11, a longa lista de exemplos de fé do Antigo Testamento, usando essa lista como motivação para os leitores continuarem numa corrida espiritual difícil.', '"Corramos com paciência a carreira que nos está proposta, olhando para Jesus, autor e consumador da fé." A imagem é atlética: despojar-se de peso, correr com resistência, manter o foco num ponto fixo à frente.', 'Testemunho de quem já atravessou dificuldades parecidas antes de você não é apenas história — funciona como plateia e incentivo ativo para continuar correndo.', '1 Coríntios 9:24-27 usa a mesma metáfora atlética: correr de forma que se alcance o prêmio, com disciplina.', true, 0);

insert into public.hero_messages (text, slug, reference, contexto, capitulo, aplicacao, conexao, is_active, sort_order)
values ('Não era a pior igreja das sete mencionadas por seus pecados óbvios — era a mais confortável, tão morna que o próprio texto diz que seria vomitada por não ser nem fria nem quente.', 'igreja-morna-de-laodiceia', 'Apocalipse 3:14-22', 'Apocalipse 2-3 registra mensagens específicas a sete igrejas na Ásia Menor, cada uma recebendo elogios e correções direcionados à sua situação particular. Laodiceia era uma cidade rica, autossuficiente economicamente.', '"Porque és morno, e não frio nem quente, vomitar-te-ei da minha boca [...] tu dizes: rico sou [...] e não sabes que és um desgraçado, e miserável, e pobre, e cego, e nu." A riqueza material tinha gerado uma cegueira espiritual sobre a própria condição real.', 'Conforto e autossuficiência aparente podem esconder uma necessidade espiritual real que só fica visível quando alguém de fora aponta com clareza.', 'Apocalipse 3:20 segue imediatamente com um convite, não uma condenação final: "eis que estou à porta, e bato".', true, 0);
