-- Divinus — fundamentação bíblica de cada sentimento (dados)

update public.feelings set
  biblico_nome = 'Marta',
  biblico_referencia = 'Lucas 10:38-42',
  biblico_versiculo = 'Marta, Marta, andas ansiosa e te preocupas com muitas coisas.',
  biblico_teaser = 'Marta se afadigava com tudo ao mesmo tempo — e foi justamente nomeada assim por Jesus, sem repreensão, só clareza.',
  biblico_contexto = 'Jesus e os discípulos chegam à casa de Marta e Maria, em Betânia, próximo de Jerusalém. É uma visita comum, sem nenhuma crise anunciada — Marta simplesmente recebe o grupo e se ocupa dos preparativos, como seria esperado de quem hospeda.',
  biblico_capitulo = 'O capítulo 10 de Lucas começa com Jesus enviando setenta discípulos em missão, e termina com essa cena doméstica em Betânia — dois modos diferentes de servir lado a lado. Marta "andava distraída" (grego perispao, "puxada em várias direções ao mesmo tempo") cuidando de "muito serviço", enquanto Maria se sentava aos pés de Jesus para ouvir. Marta se aproxima e faz uma pergunta carregada de mágoa: "Senhor, não se te dá que minha irmã me deixe servir só? Dize-lhe, pois, que me ajude." A resposta de Jesus repete o nome dela duas vezes — um recurso hebraico de ênfase e ternura, não de repreensão dura — e nomeia com precisão o que estava acontecendo: ela andava "ansiosa e turbada" (merimnas kai thorybaze, literalmente "dividida em pedaços e em tumulto") por muitas coisas, quando "uma só é necessária". Jesus não diz que o serviço de Marta era errado; diz que a agitação interna que vinha junto dele estava roubando dela a própria capacidade de estar presente. Maria, diz ele, "escolheu a boa parte, que não lhe será tirada" — uma escolha, não um talento nato.',
  biblico_aplicacao = 'A cena não ensina que servir é ruim e contemplar é bom — ensina que dá para fazer a mesma tarefa de dois jeitos: fragmentado por ansiedade ou presente nela. Antes de julgar Marta, vale notar: ela é quem convida Jesus para dentro de casa. O problema nunca foi o serviço, foi a ansiedade que o acompanhava.',
  biblico_conexao = 'Filipenses 4:6-7 dá o antídoto prático que Marta ainda não tinha: apresentar tudo em oração com ação de graças, recebendo de volta "a paz de Deus, que excede todo o entendimento". João 11:1-44, mais adiante no mesmo evangelho, mostra a mesma Marta — agora no luto pela morte do irmão Lázaro — declarando com firmeza: "Eu sei que ele há de ressuscitar [...] eu creio que tu és o Cristo", como se a lição daquele dia em sua própria casa tivesse enraizado.'
where slug = 'ansiedade';

update public.feelings set
  biblico_nome = 'Os discípulos trancados',
  biblico_referencia = 'João 20:19-21',
  biblico_versiculo = 'Estando as portas fechadas, onde os discípulos, com medo dos judeus, estavam reunidos [...] chegou Jesus, e pôs-se no meio.',
  biblico_teaser = 'Eles trancaram tudo por medo — e foi exatamente ali, do lado de dentro do medo, que a paz chegou primeiro.',
  biblico_contexto = 'É a noite do primeiro dia da semana, o próprio dia da ressurreição. As mulheres já tinham relatado o túmulo vazio, mas os discípulos ainda não tinham processado o que isso significava. Jerusalém continuava sob controle das mesmas autoridades religiosas que tinham condenado Jesus à morte poucos dias antes.',
  biblico_capitulo = 'João 20 registra três aparições no mesmo capítulo: a Maria Madalena no túmulo, aos discípulos trancados à noite, e a Tomé uma semana depois. Na segunda cena, o texto é específico sobre o motivo do trancamento: "por medo dos judeus" — não um medo vago, um medo concreto de perseguição, prisão, talvez execução, pela mesma estrutura de poder que tinha acabado de matar seu líder. Portas fechadas, numa casa numa cidade pequena, não impediam fisicamente uma invasão — eram mais um gesto simbólico de proteção do que segurança real. É nesse cenário exato que o texto diz "chegou Jesus, e pôs-se no meio deles", sem que a porta tivesse sido aberta. A primeira frase que ele diz não é uma repreensão pelo medo, nem uma exigência de que saíssem do esconderijo: "Paz seja convosco." Ele repete a saudação, mostra as mãos e o lado — prova de identidade, não exigência de coragem — e só depois comissiona: "Assim como o Pai me enviou, também eu vos envio." O envio vem depois da paz, não antes dela.',
  biblico_aplicacao = 'O texto não retrata coragem instantânea substituindo o medo — retrata presença chegando até dentro do esconderijo, antes de qualquer mudança de comportamento exigida. Os discípulos só saem daquele quarto depois, gradualmente; a transformação de "trancados por medo" para "testemunhas públicas" (visível em Atos 2) leva semanas, não um instante.',
  biblico_conexao = '2 Timóteo 1:7 nomeia o oposto do espírito de temor: "fortaleza, e de amor, e de moderação". Isaías 41:10 promete a mesma companhia que tornou o medo administrável, não ausente: "não temas, porque eu sou contigo". Marcos 4:40, na tempestade, mostra Jesus perguntando aos discípulos "por que sois assim tímidos?" — a mesma pergunta implícita, mas ali ainda em processo, aqui já em algum grau resolvida pela presença.'
where slug = 'medo';

update public.feelings set
  biblico_nome = 'Jesus no Getsêmani',
  biblico_referencia = 'Lucas 22:39-46',
  biblico_versiculo = 'E, posto em agonia, orava mais intensamente. E o seu suor tornou-se em grandes gotas de sangue, que caíam sobre a terra.',
  biblico_teaser = 'Antes de qualquer sofrimento visível, o corpo dele já respondia à angústia como se fosse sangue — e ele continuou orando dentro dela.',
  biblico_contexto = 'É a última noite antes da crucificação. Jesus acabou de instituir a ceia com os discípulos e sabe exatamente o que está por vir: prisão, julgamento injusto, tortura, morte. Ele se retira para orar no monte das Oliveiras, num lugar chamado Getsêmani, levando consigo Pedro, Tiago e João, mas orando sozinho, "a distância de um tiro de pedra".',
  biblico_capitulo = 'Os quatro evangelhos registram esse momento com detalhes ligeiramente diferentes, mas Lucas é o único que descreve o suor como sangue — um fenômeno médico real chamado hematidrose, associado a estresse fisiológico extremo, quando pequenos vasos sanguíneos ao redor das glândulas sudoríparas se rompem sob pressão emocional intensa. Jesus pede três vezes, segundo o relato paralelo de Mateus 26:39-44, que o "cálice" passasse dele, terminando cada oração com "não seja como eu quero, mas como tu queres". Um anjo aparece para fortalecê-lo — nem a angústia nem a oração cessam com a chegada do anjo; ambas continuam, "orava mais intensamente". Enquanto isso, os discípulos, levados por tristeza e cansaço, dormem repetidamente, incapazes de "vigiar uma hora" com ele. A cena termina com Judas chegando com a multidão armada — a angústia da oração dá lugar imediatamente à ação da prisão, sem pausa de recuperação entre uma coisa e outra.',
  biblico_aplicacao = 'A angústia registrada aqui não é fraqueza de fé — é a reação humana genuína de alguém plenamente consciente do sofrimento à frente, orando dentro dela em vez de fugir dela. A oração não elimina a angústia antes de agir; ela sustenta a pessoa através da angústia até o momento de agir.',
  biblico_conexao = 'Hebreus 5:7-8 comenta esse episódio diretamente: Jesus "ofereceu orações e súplicas, com grande clamor e lágrimas [...] e, aprendendo, ainda que era Filho, a obediência, por aquilo que padeceu". Salmos 42:5-6 nomeia a mesma angústia em forma de pergunta: "por que te abates, ó minha alma, e por que te perturbas dentro de mim?" Mateus 26:38 registra Jesus descrevendo o próprio estado aos discípulos: "a minha alma está cheia de tristeza até a morte".'
where slug = 'angustia';

update public.feelings set
  biblico_nome = 'A multidão do Sermão do Monte',
  biblico_referencia = 'Mateus 6:25-34',
  biblico_versiculo = 'Não andeis, pois, cuidadosos pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu próprio mal.',
  biblico_teaser = 'Ele ensinou sobre não se preocupar a gente que genuinamente não sabia se teria o que comer amanhã — não era teoria distante.',
  biblico_contexto = 'O Sermão do Monte, registrado em Mateus 5-7, é o bloco de ensino mais extenso de Jesus, dirigido a uma multidão majoritariamente galileia — camponeses, pescadores, artesãos, gente vivendo perto da linha da subsistência sob a economia extrativista do Império Romano. Preocupação com comida e roupa não era abstração para essa plateia.',
  biblico_capitulo = 'O capítulo 6 já vinha tratando de práticas religiosas feitas para impressionar (esmola, oração, jejum) e do problema de servir a dois senhores — Deus e as riquezas. É dentro dessa linha de raciocínio sobre onde depositar confiança que Jesus chega à preocupação: "não andeis cuidadosos [...] pela vossa vida, sobre o que haveis de comer [...] nem pelo vosso corpo, sobre o que haveis de vestir". Ele usa dois exemplos da própria paisagem galileia: as aves do céu, que "não semeiam, nem segam, nem ajuntam em celeiros", e ainda assim são alimentadas; e os lírios do campo, que "não trabalham nem fiam", e ainda assim estão vestidos com mais esplendor do que Salomão em toda a sua glória — uma referência ao rei mais rico da história de Israel, cuja riqueza lendária ainda assim não se compara à beleza natural de uma flor comum. O argumento culmina numa pergunta retórica: "e qual de vós, por mais cuidadoso que ande, poderá acrescentar um côvado à sua estatura?" — preocupação não muda o resultado, só consome o presente. A instrução final reordena prioridade: "buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas", seguida da frase que fecha o capítulo: o amanhã cuidará de si mesmo, e basta a cada dia o seu próprio mal.',
  biblico_aplicacao = 'A instrução não vem de alguém alheio à necessidade real — vem de um mestre itinerante sem casa própria ("as raposas têm covis [...] mas o Filho do homem não tem onde reclinar a cabeça", Mateus 8:20), ensinando gente pobre. Preocupação, no argumento de Jesus, não é neutra: ela rouba hoje pagando um imposto sobre um amanhã que ainda nem chegou.',
  biblico_conexao = 'Filipenses 4:6-7 traduz o mesmo princípio em prática concreta: apresentar pedidos com ação de graças, em troca de paz que excede o entendimento. 1 Pedro 5:7 dá o destino certo da preocupação: "lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós". Êxodo 16, o maná no deserto, já tinha ensinado o mesmo princípio de provisão diária séculos antes, sem acúmulo permitido além do necessário para aquele dia.'
where slug = 'preocupacao';

update public.feelings set
  biblico_nome = 'Os discípulos a caminho de Emaús',
  biblico_referencia = 'Lucas 24:13-27',
  biblico_versiculo = 'E, estando eles falando entre si, e fazendo perguntas um ao outro [...] tinham os olhos como que fechados, para que o não conhecessem.',
  biblico_teaser = 'Eles conheciam todos os fatos e ainda assim não entendiam nada — a resposta caminhava literalmente ao lado deles.',
  biblico_contexto = 'É o mesmo dia da ressurreição, mais tarde. Dois discípulos — um chamado Cleopas, o outro não nomeado — deixam Jerusalém rumo a Emaús, uma vila a cerca de onze quilômetros de distância, processando em voz alta os eventos dos últimos três dias: a prisão, a crucificação, e agora relatos confusos de mulheres sobre um túmulo vazio e uma visão de anjos.',
  biblico_capitulo = 'Lucas descreve os dois discípulos "tristes", discutindo "todas aquelas coisas que tinham acontecido", quando "o mesmo Jesus se aproximou, e ia com eles" — mas o texto explica diretamente por que não o reconheceram: "os olhos deles estavam como que fechados". Jesus pergunta do que estão falando, e Cleopas responde surpreso que ele parece ser o único visitante de Jerusalém sem saber "as coisas que nela têm sucedido" — a ironia é que é exatamente Jesus quem sabe mais sobre esses eventos do que qualquer um dos dois. Eles resumem os fatos com precisão: um profeta poderoso em obras e palavras, entregue à morte pelos principais sacerdotes, e a esperança frustrada de que "fosse ele quem havia de remir Israel". Mencionam ainda o relato das mulheres sobre o túmulo vazio e a visão de anjos, mas concluem com uma admissão de confusão total — tinham os fatos, não tinham o sentido. É só então que Jesus os repreende com carinho por serem "tardos de coração para crer tudo o que os profetas disseram", e começando por Moisés e todos os profetas, "lhes declarava em todas as Escrituras o que dele estava escrito" — uma aula bíblica inteira, dada por ele mesmo, sobre ele mesmo, antes de ser reconhecido.',
  biblico_aplicacao = 'Ter todos os dados corretos e ainda assim não conseguir montar o quadro completo não é falha de inteligência nem de fé — é um estado registrado na própria Bíblia, corrigido não por mais esforço próprio, mas por alguém que se aproxima e explica, mesmo sem ser reconhecido de imediato.',
  biblico_conexao = 'O reconhecimento final só acontece em Lucas 24:30-31, quando Jesus parte o pão à mesa — "abriram-se-lhes os olhos, e o conheceram". Provérbios 3:5-6 recomenda não se apoiar apenas no próprio entendimento. João 16:12-13 promete o Espírito Santo especificamente como guia "a toda a verdade", quando o entendimento humano sozinho não é suficiente.'
where slug = 'confusao';

update public.feelings set
  biblico_nome = 'Noemi',
  biblico_referencia = 'Rute 1:1-21',
  biblico_versiculo = 'Não me chameis Noemi; chamai-me Mara, porque o Todo-Poderoso me encheu de grande amargura.',
  biblico_teaser = 'Ela pediu pra trocar o próprio nome — de "agradável" para "amargura" — recusando esconder a tristeza atrás de uma fachada.',
  biblico_contexto = 'Uma fome em Belém leva Elimeleque, sua esposa Noemi e os dois filhos a emigrarem para Moabe, território estrangeiro e historicamente hostil a Israel. Lá, Elimeleque morre; os filhos se casam com mulheres moabitas, Orfa e Rute; anos depois, os dois filhos também morrem, deixando Noemi viúva, sem filhos, numa terra que não era a sua, com duas noras estrangeiras.',
  biblico_capitulo = 'O livro de Rute abre com uma sequência de perdas comprimida em poucos versículos: fome, migração, três mortes na família em sucessão. Ao saber que a fome em Belém tinha terminado, Noemi decide voltar, e libera as noras para voltarem às próprias famílias, reconhecendo abertamente a própria situação: "grande amargura tenho eu mais do que vós, porque a mão do Senhor saiu contra mim". Orfa aceita e volta; Rute insiste em ficar, com o discurso de lealdade que se tornou símbolo ("aonde quer que fores irei eu"). Quando as duas chegam a Belém, toda a cidade se agita, e as mulheres perguntam: "não é esta Noemi?" A resposta dela recusa a pergunta pelo nome antigo: "não me chameis Noemi (que significa "minha doçura" ou "agradável"); chamai-me Mara ("amargura"), porque o Todo-Poderoso me encheu de amargura amargamente. Cheia parti, porém vazia o Senhor me tornou a trazer." É uma reclamação direta a Deus, nomeada em praça pública, sem suavização nem tentativa de parecer bem diante da comunidade.',
  biblico_aplicacao = 'Noemi não esconde a tristeza atrás de otimismo forçado nem de linguagem religiosa polida — ela nomeia a dor pelo nome certo, publicamente. É justamente a partir desse ponto de honestidade total, e não antes dele, que o livro começa a construir a restauração: Rute encontra Boaz, e Noemi termina o livro segurando o neto no colo.',
  biblico_conexao = 'Salmos 34:18 promete companhia específica nesse estado: "perto está o Senhor dos que têm o coração quebrantado". Eclesiastes 3:4 inclui "tempo de chorar" na mesma lista que "tempo de rir", sem hierarquia entre os dois. Rute 4:14-17 mostra o desfecho: as mesmas mulheres que a viram voltar vazia agora celebram um neto que "será restaurador de tua vida".'
where slug = 'tristeza';

update public.feelings set
  biblico_nome = 'Davi por Absalão',
  biblico_referencia = '2 Samuel 18:1-33',
  biblico_versiculo = 'Meu filho Absalão, meu filho, meu filho Absalão! Quem me dera que eu morrera por ti, Absalão, meu filho, meu filho!',
  biblico_teaser = 'Ele venceu a guerra contra o próprio filho rebelde — e a vitória virou um dos lamentos mais crus de toda a Bíblia.',
  biblico_contexto = 'Absalão, terceiro filho de Davi, organiza uma rebelião armada contra o pai depois de anos de ressentimento acumulado (incluindo a resposta insuficiente de Davi ao estupro de sua irmã Tamar por outro filho, Amnom). A rebelião chega a forçar Davi a fugir de Jerusalém antes do confronto militar final na floresta de Efraim.',
  biblico_capitulo = 'Antes da batalha, Davi dá uma ordem pública e específica aos comandantes: "tratai brandamente, por amor de mim, com o rapaz, com Absalão" — mesmo organizando a guerra contra o próprio filho, ele ainda pede clemência. Durante o combate, Absalão fica preso pelos cabelos num carvalho enquanto sua mula passa por baixo dos galhos, e Joabe, general de Davi, o mata diretamente contra a ordem recebida. Dois mensageiros correm para informar Davi do resultado da batalha; o rei, esperando no portão da cidade, pergunta antes de qualquer outra coisa: "há paz com o mocinho Absalão?" Quando finalmente recebe a notícia da morte do filho, a reação de Davi não tem nenhum traço de alívio político, mesmo tendo acabado de vencer uma rebelião que ameaçava seu trono e sua vida: ele sobe ao quarto por cima da porta, chorando, repetindo o nome do filho seis vezes em duas frases — "meu filho Absalão, meu filho, meu filho Absalão! Quem me dera que eu morrera por ti, Absalão, meu filho, meu filho!" O capítulo seguinte mostra Joabe repreendendo Davi por chorar publicamente por quem tinha tentado matá-lo, envergonhando os soldados que arriscaram a vida por ele — mas o texto não corrige nem suaviza o luto de Davi, só registra a tensão entre luto pessoal e responsabilidade pública.',
  biblico_aplicacao = 'O luto de Davi não exige que a relação com Absalão tivesse sido saudável, nem que a rebelião não tivesse acontecido. Amor genuíno e mágoa genuína, mesmo depois da pior traição possível, podem ocupar o mesmo coração ao mesmo tempo — o texto não tenta resolver essa tensão, só a registra com total honestidade.',
  biblico_conexao = 'João 11:35, o versículo mais curto da Bíblia em português ("chorou Jesus"), mostra a mesma permissão para lágrimas mesmo sabendo do que viria depois. Salmos 103:13-14 descreve a compaixão de Deus como a de um pai pelos filhos, "lembrado de que somos pó". Gênesis 37:34-35, o luto de Jacó por José (que ele acreditava morto), mostra outro pai recusando ser consolado por muitos dias.'
where slug = 'luto';

update public.feelings set
  biblico_nome = 'Elias no deserto',
  biblico_referencia = '1 Reis 19:1-18',
  biblico_versiculo = 'E eu, eu só, fiquei; e procuram tirar-me a vida, para haver-ma.',
  biblico_teaser = 'Ele repetiu duas vezes que era o único fiel que restava — e a resposta revelou que havia sete mil que ele nem sabia que existiam.',
  biblico_contexto = 'Elias acabou de vencer, sozinho, quatrocentos e cinquenta profetas de Baal num confronto público no monte Carmelo, prova espetacular do poder de Deus diante de todo o povo de Israel. Horas depois, a rainha Jezabel jura matá-lo em até vinte e quatro horas, e Elias foge para o deserto, andando um dia inteiro sozinho.',
  biblico_capitulo = 'Exausto, Elias se senta debaixo de um zimbro e pede para morrer; depois de ser alimentado e descansar duas vezes por intervenção angélica, ele caminha quarenta dias até o monte Horebe (o mesmo Sinai onde Moisés recebera a lei). Ali, numa caverna, Deus pergunta: "que fazes aqui, Elias?" A resposta de Elias é uma queixa dupla, repetida quase palavra por palavra duas vezes no mesmo capítulo (versículos 10 e 14): "tenho sido muito zeloso pelo Senhor [...] mataram os teus profetas à espada, e só eu fiquei; e procuram tirar-me a vida." Não é exagero pontual — é a mesma frase repetida depois de Deus já ter passado por vento forte, terremoto e fogo diante dele, nenhum contendo sua presença, até vir "uma voz mansa e delicada". Mesmo depois desse encontro íntimo, Elias repete a queixa de solidão total pela segunda vez, exatamente com as mesmas palavras. Só então Deus revela algo que Elias não tinha nenhuma forma de saber: "deixei ficar em Israel sete mil, todos os joelhos que não se dobraram a Baal." Elias, o profeta mais visível de toda uma geração, desconhecia completamente a existência de milhares de pessoas fiéis como ele.',
  biblico_aplicacao = 'A sensação de estar completamente sozinho pode ser genuína e ainda assim numericamente incorreta. Elias não estava mentindo nem exagerando de propósito — ele simplesmente não tinha acesso à informação que mudaria por completo sua percepção da própria solidão. A resposta de Deus não repreende o sentimento, complementa a informação incompleta por trás dele.',
  biblico_conexao = 'Hebreus 13:5 promete a companhia que Elias não conseguia sentir: "não te deixarei, nem te desampararei". Salmos 34:18 e Salmos 68:6 ("Deus faz que o solitário viva em família") tratam do mesmo tema. Romanos 11:2-4 cita diretamente esse episódio de Elias como exemplo de como a percepção humana de estar sozinho pode ignorar um remanescente maior do que se imagina.'
where slug = 'solidao';

update public.feelings set
  biblico_nome = 'Jesus na cruz',
  biblico_referencia = 'Mateus 27:45-46',
  biblico_versiculo = 'Deus meu, Deus meu, por que me desamparaste?',
  biblico_teaser = 'No momento de maior sofrimento, ele gritou a mesma pergunta que qualquer pessoa abandonada já gritou — sem disfarçar nada.',
  biblico_contexto = 'Jesus está sendo crucificado, tendo já sofrido açoites, zombaria pública e horas penduradas na cruz. O texto marca que, da hora sexta até a hora nona (aproximadamente meio-dia às três da tarde), "houve trevas sobre toda a terra" — um escurecimento notado por historiadores da época como fenômeno incomum.',
  biblico_capitulo = 'Perto da hora nona, Jesus "clamou com grande voz", citando em aramaico o início do Salmo 22: "Eli, Eli, lamá sabactâni?" — traduzido no próprio texto como "Deus meu, Deus meu, por que me desamparaste?". Alguns dos que ouviram, confundindo o som, acharam que ele chamava por Elias. É o único momento registrado em toda a narrativa dos evangelhos em que Jesus não se dirige a Deus como "Pai" — em todas as outras orações registradas (incluindo o Getsêmani, horas antes), ele usa "Pai" ou "Aba, Pai". Aqui, a forma de tratamento muda para "Deus meu", uma distância relacional nomeada em voz alta, publicamente, no momento de maior sofrimento físico e espiritual. O Salmo 22, que Jesus cita de memória (prática comum entre judeus devotos, que memorizavam os salmos), não é só um grito de abandono — o mesmo salmo, se continuado, vira uma declaração de confiança e louvor nos versículos finais, o que sugere que Jesus pode estar invocando o salmo inteiro, não apenas sua primeira linha, mesmo citando só o começo em voz alta na cruz.',
  biblico_aplicacao = 'Sentir-se abandonado, inclusive por Deus, no momento de maior dor, tem precedente direto no próprio Jesus — não é evidência de falta de fé, é uma experiência registrada exatamente no centro da narrativa cristã. Gritar essa sensação em voz alta, sem disfarce religioso, é uma forma legítima de oração, não o oposto dela.',
  biblico_conexao = 'Salmos 22 inteiro é o pano de fundo direto dessa citação — começa em abandono ("por que me desamparaste?") e termina em louvor ("todos os confins da terra se lembrarão"). Hebreus 13:5 promete o oposto permanente desse abandono momentâneo: "não te deixarei, nem te desampararei". Romanos 8:32 argumenta que, se Deus não poupou o próprio Filho, "como não nos dará também com ele todas as coisas?" — o abandono da cruz sendo parte de um propósito maior, não rejeição definitiva.'
where slug = 'abandono';

update public.feelings set
  biblico_nome = 'José vendido pelos irmãos',
  biblico_referencia = 'Gênesis 37:1-36',
  biblico_versiculo = 'E, quando José veio a seus irmãos, tiraram-lhe a sua túnica [...] e lançaram-no na cova [...] e o venderam.',
  biblico_teaser = 'Rejeitado pela própria família da forma mais concreta possível — vendido como mercadoria — antes de qualquer redenção aparecer no horizonte.',
  biblico_contexto = 'José é o décimo primeiro dos doze filhos de Jacó, mas o primeiro de Raquel, a esposa mais amada — e Jacó "amava mais a José do que a todos os seus filhos", presenteando-o com uma túnica especial (tradicionalmente traduzida "de várias cores", possivelmente uma túnica longa que dispensava trabalho manual, sinal de status). Os irmãos mais velhos percebem o favoritismo e o odeiam por causa disso.',
  biblico_capitulo = 'O ódio dos irmãos aumenta quando José relata dois sonhos onde feixes de trigo e depois o sol, a lua e onze estrelas se curvam diante dele — interpretados corretamente como visões de liderança futura sobre a própria família. Quando José é enviado pelo pai para verificar os irmãos que pastoreavam longe de casa, eles o avistam de longe e conspiram: "eis que lá vem o sonhador. Vinde, pois, agora, e matemo-lo." Rúben, o mais velho, intervém para que não o matassem diretamente, sugerindo lançá-lo numa cova vazia no deserto, com plano secreto de resgatá-lo depois. Os irmãos tiram a túnica especial de José, símbolo do favoritismo, e o lançam na cova. Enquanto comem tranquilamente por perto, avistam uma caravana de mercadores ismaelitas indo para o Egito, e Judá propõe vendê-lo em vez de deixá-lo morrer na cova — "que proveito haverá que matemos a nosso irmão?" José é vendido por vinte moedas de prata, o preço padrão de um escravo. Os irmãos mergulham a túnica no sangue de um bode e a levam a Jacó, que conclui que uma fera devorou o filho, e "chorou por ele muitos dias", recusando ser consolado. José, entretanto, é levado ao Egito como escravo — rejeitado pela própria família, sem nenhuma indicação no texto, naquele momento, de que a história teria um desfecho diferente.',
  biblico_aplicacao = 'A rejeição de José não veio de estranhos — veio das pessoas mais próximas, motivada por inveja e favoritismo mal administrado por todos os lados, inclusive pelo próprio pai. O texto não minimiza a gravidade do que aconteceu, nem oferece consolo imediato — a virada só vem capítulos depois, e José precisa atravessar anos de escravidão e prisão injusta antes dela.',
  biblico_conexao = 'Isaías 53:3 descreve o servo sofredor como alguém "desprezado e rejeitado dos homens", um padrão que se repete. Salmos 27:10 promete acolhimento mesmo quando a rejeição vem da própria família: "quando meu pai e minha mãe me desampararem, o Senhor me recolherá". Gênesis 50:20, décadas depois, mostra José resumindo toda a história: "vós, na verdade, intentastes o mal contra mim, porém Deus o intentou para o bem".'
where slug = 'rejeicao';

update public.feelings set
  biblico_nome = 'Os discípulos voltam a pescar',
  biblico_referencia = 'João 21:1-14',
  biblico_versiculo = 'Disse-lhes Simão Pedro: vou pescar. Disseram-lhe eles: também nós vamos contigo. [...] E aquela noite nada apanharam.',
  biblico_teaser = 'Depois de tudo que tinham vivido, eles voltaram à vida antiga — e nem isso deu certo, até uma voz na praia mudar tudo de novo.',
  biblico_contexto = 'Jesus já tinha ressuscitado e aparecido aos discípulos duas vezes (João 20). Mesmo assim, um grupo de sete discípulos, incluindo Pedro, Tomé, Natanael, Tiago e João, se encontra à beira do mar da Galileia (também chamado Tibérias), aparentemente sem instrução clara sobre o que fazer a seguir.',
  biblico_capitulo = 'Pedro anuncia, sem grande explicação: "vou pescar" — um retorno à profissão original, de antes do chamado de Jesus (Lucas 5:1-11 registra o primeiro chamado de Pedro exatamente na mesma atividade). Os outros o acompanham, talvez por falta de outra direção clara. Eles pescam a noite inteira — período tradicional de pesca na região — e "nada apanharam", um esforço completo sem nenhum resultado, o tipo de fracasso que amplifica desânimo já presente. Ao amanhecer, uma figura na praia, ainda não reconhecida, pergunta se têm algum peixe, e sugere lançar a rede do lado direito do barco. A pesca resultante é tão grande — cento e cinquenta e três peixes grandes, contados especificamente pelo texto — que João reconhece: "é o Senhor!" Pedro, impulsivo como sempre, veste a roupa (estava sem ela para trabalhar) e pula na água para chegar até a praia antes dos outros. Jesus já tinha preparado brasas, peixe e pão — um café da manhã pronto, sem que ninguém tivesse pedido — antes da conversa mais importante daquela manhã, a restauração de Pedro, que viria logo em seguida.',
  biblico_aplicacao = 'Desânimo, mesmo depois de já ter vivido algo extraordinário, pode empurrar de volta à rotina antiga por falta de clareza sobre o próximo passo — isso não invalida o que já foi vivido, só marca uma pausa. E a mesma pausa pode ser interrompida por uma provisão inesperada, chegando antes mesmo de qualquer pedido ser feito.',
  biblico_conexao = 'Gálatas 6:9 fala diretamente do tempo certo da colheita, "se não houvermos desfalecido". Lucas 5:4-6, o primeiro chamado de Pedro, tem a mesma estrutura: noite sem nada, instrução de Jesus, rede cheia — o padrão se repete no início e quase no fim do ministério de Pedro. Isaías 40:31 promete renovação de forças especificamente para quem está no fim das próprias.'
where slug = 'desanimo';

update public.feelings set
  biblico_nome = 'Os discípulos em Emaús',
  biblico_referencia = 'Lucas 24:13-24',
  biblico_versiculo = 'Nós esperávamos que fosse ele quem havia de remir Israel; e, com tudo isto, é já hoje o terceiro dia que estas coisas aconteceram.',
  biblico_teaser = 'A frase está no passado — "nós esperávamos" — como se aquela esperança já tivesse morrido junto com os últimos três dias.',
  biblico_contexto = 'No mesmo dia da ressurreição, dois discípulos caminham de Jerusalém a Emaús processando os eventos recentes: a prisão, a crucificação pública de Jesus, e relatos ainda não confirmados de mulheres sobre um túmulo vazio.',
  biblico_capitulo = 'Quando um viajante desconhecido (Jesus, ainda não reconhecido) pergunta do que estão falando, Cleopas resume os fatos com precisão jornalística: um profeta "poderoso em obras e em palavras diante de Deus e de todo o povo", entregue pelos principais sacerdotes "para ser condenado à morte, e o crucificaram". A frase central vem em seguida, marcada gramaticalmente no passado: "nós esperávamos que fosse ele quem havia de remir Israel" — o verbo no imperfeito sugere uma esperança sustentada por tempo, agora tratada como encerrada. Cleopas acrescenta o detalhe temporal específico — "é já hoje o terceiro dia" — como se o prazo natural para qualquer reviravolta já tivesse passado. Ele menciona, quase de passagem, o relato das mulheres sobre anjos e o túmulo vazio, e que alguns discípulos foram conferir e "a ele não o viram" — informação que tinham, mas que não tinha sido suficiente para reacender a esperança perdida. A ironia estrutural da cena é que a própria pessoa cuja "morte" eles lamentavam estava caminhando ao lado deles, ouvindo o próprio funeral sendo narrado em primeira pessoa.',
  biblico_aplicacao = 'Descrever uma esperança no passado, como algo que já morreu, é uma reação genuína e registrada na Bíblia, não sinal de fraqueza espiritual. O que muda a cena não é esforço próprio dos discípulos para se animarem — é a revelação de que a esperança que consideravam morta estava, na verdade, viva e caminhando bem ao lado deles o tempo todo.',
  biblico_conexao = 'Romanos 15:13 chama Deus diretamente de "Deus de esperança", capaz de fazer "abundar em esperança" quem está esgotado dela. Lamentações 3:21-23, escrito em meio à destruição de Jerusalém, faz o mesmo movimento: de desespero total para "as suas misericórdias se renovam cada manhã". Jeremias 29:11 promete "pensamentos de paz, e não de mal" a um povo exilado sem nenhuma esperança visível de retorno próximo.'
where slug = 'desesperanca';

update public.feelings set
  biblico_nome = 'Salomão em Eclesiastes',
  biblico_referencia = 'Eclesiastes 1:1-2:11',
  biblico_versiculo = 'Vaidade de vaidades, tudo é vaidade [...] eis que tudo era vaidade e aflição de espírito, e proveito nenhum havia debaixo do sol.',
  biblico_teaser = 'O homem com acesso a qualquer prazer, projeto ou conquista possível testou tudo — e concluiu que nada disso, sozinho, era suficiente.',
  biblico_contexto = 'Eclesiastes é tradicionalmente atribuído a Salomão, filho de Davi, rei de Israel no auge de seu poder e riqueza — construtor do templo, autor de milhares de provérbios e cânticos segundo 1 Reis 4:32, com acesso irrestrito a qualquer projeto, prazer ou conhecimento que desejasse experimentar.',
  biblico_capitulo = 'O livro abre com a frase que define seu tom: "vaidade de vaidades, tudo é vaidade" — a palavra hebraica hevel significa literalmente "vapor" ou "sopro", algo que se dissipa antes que se consiga segurar. O autor, identificado como "o pregador, filho de Davi, rei em Jerusalém", descreve metodicamente cada experimento que realizou: buscou sabedoria e conhecimento em profundidade (1:12-18), concluindo que "na muita sabedoria há muito enfado"; construiu casas, plantou vinhas, jardins e pomares, fez reservatórios de água, acumulou servos, gado, prata e ouro "mais do que todos os que houve antes de mim em Jerusalém" (2:4-9); não recusou aos olhos nada que desejassem, nem impediu o coração de nenhuma alegria (2:10). A conclusão, depois de esgotar sistematicamente riqueza, prazer, sabedoria e realização, é direta: "olhei eu para todas as obras que as minhas mãos fizeram [...] e eis que tudo era vaidade e aflição de espírito, e proveito nenhum havia debaixo do sol" (2:11). O livro não termina em niilismo total — mais adiante, o capítulo 3 traz o famoso poema sobre tempos determinados para cada coisa, e o livro se fecha (12:13) com uma conclusão prática: "teme a Deus, e guarda os seus mandamentos, porque isto é todo o dever do homem".',
  biblico_aplicacao = 'Vazio, no relato de Salomão, não é falha de gratidão nem falta de esforço — é o resultado documentado de buscar plenitude em qualquer coisa "debaixo do sol", isolada de uma referência maior. A conclusão do livro não é parar de trabalhar, construir ou desfrutar, é parar de esperar que essas coisas, sozinhas, preencham o que foram feitas para apontar além de si mesmas.',
  biblico_conexao = 'João 4:13-14 oferece diretamente o que Salomão ainda não tinha nomeado: uma água que sacia definitivamente, "nunca mais terá sede". Mateus 6:19-21 recomenda não acumular tesouros que "a traça e a ferrugem consomem". Filipenses 4:11-12 mostra Paulo, séculos depois, chegando a uma versão diferente da mesma conclusão: "aprendi a contentar-me com o que tenho".'
where slug = 'vazio';

update public.feelings set
  biblico_nome = 'Moisés quebra as tábuas',
  biblico_referencia = 'Êxodo 32:1-20',
  biblico_versiculo = 'E aconteceu que, chegando ele ao arraial, e vendo o bezerro e as danças, a ira de Moisés se acendeu, e lançou as tábuas das suas mãos, e as quebrou ao pé do monte.',
  biblico_teaser = 'Ele descia com as próprias tábuas da lei, escritas pelo dedo de Deus — e as quebrou no chão diante de uma traição concreta.',
  biblico_contexto = 'Moisés está no monte Sinai há quarenta dias recebendo instruções detalhadas de Deus, incluindo as duas tábuas de pedra da lei, "escritas pelo dedo de Deus". Enquanto isso, o povo no acampamento, impaciente com a demora, pede a Arão que faça "deuses que vão adiante de nós".',
  biblico_capitulo = 'Arão recolhe os brincos de ouro do povo e funde um bezerro, ao qual o povo declara: "este é o teu deus, ó Israel, que te tirou da terra do Egito" — atribuindo a um objeto recém-fabricado o que Deus tinha acabado de fazer pessoalmente. Constroem um altar e organizam uma festa com holocaustos, comida e dança. Deus avisa Moisés no monte sobre o que está acontecendo, chamando o povo de "corrompido" e propondo consumi-los em ira, poupando só Moisés para começar uma nova nação — Moisés intercede, lembrando a Deus das promessas feitas a Abraão, Isaque e Israel, e "o Senhor se arrependeu do mal que dissera havia de fazer ao seu povo". Quando Moisés finalmente desce o monte e se aproxima do arraial, ele vê com os próprios olhos o bezerro e as danças — e sua reação é imediata e física: "a ira de Moisés se acendeu, e lançou as tábuas das suas mãos, e as quebrou ao pé do monte". Ele queima o bezerro, mói-o até virar pó, espalha na água e faz o povo beber. Depois confronta Arão diretamente, e organiza uma resposta mais severa através dos filhos de Levi. As tábuas quebradas — literalmente a lei de Deus, recém-recebida, destruída no chão — são depois refeitas por instrução divina no capítulo seguinte, mas o gesto de quebrá-las registra o tamanho da traição que Moisés testemunhou.',
  biblico_aplicacao = 'A raiva de Moisés não é apresentada como pecado automático — é uma resposta proporcional a uma traição real e concreta, presenciada diretamente. O que exige mais atenção no relato não é o sentimento em si, mas a sequência de ações que vêm depois dele: confronto direto, intercessão renovada, e reconstrução do que foi quebrado.',
  biblico_conexao = 'Efésios 4:26 estabelece o limite prático: "irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira". Tiago 1:19-20 recomenda ser "tardio para se irar", porque "a ira do homem não opera a justiça de Deus". Números 20:10-12, mais adiante, mostra um episódio de raiva de Moisés que teve consequências graves — ferir a rocha em vez de falar com ela — um contraste que sugere que nem toda raiva de Moisés teve o mesmo resultado.'
where slug = 'raiva';

update public.feelings set
  biblico_nome = 'Esaú contra Jacó',
  biblico_referencia = 'Gênesis 27:1-45',
  biblico_versiculo = 'E Esaú aborreceu a Jacó por causa da bênção com que seu pai o tinha abençoado; e disse Esaú no seu coração: [...] então matarei a Jacó, meu irmão.',
  biblico_teaser = 'A mágoa não explodiu na hora — ele planejou guardá-la até o momento certo, esperando o pai morrer para agir.',
  biblico_contexto = 'Jacó já tinha comprado a primogenitura de Esaú por um prato de comida anos antes (Gênesis 25:29-34). Agora, com Isaque velho e quase cego, Rebeca arma um plano para que Jacó, disfarçado com peles de cabrito nos braços e vestindo roupas de Esaú, engane o pai e receba a bênção paterna reservada ao filho mais velho.',
  biblico_capitulo = 'O engano funciona: Isaque, confuso pela voz de Jacó mas convencido pelo tato e cheiro das roupas de Esaú, concede a bênção — fertilidade, prosperidade, e a posição de senhor sobre os próprios irmãos, incluindo Esaú. Quando Esaú retorna da caça e descobre o que aconteceu, o texto descreve sua reação em detalhe: ele "clamou com grande e mui amargo brado", pedindo ao pai uma bênção também, mas Isaque responde que já não havia mais nada para dar — a bênção principal já tinha sido entregue e não podia ser repetida ou revertida. Esaú chora abertamente diante do pai, um dos poucos momentos de choro masculino registrado com tanto detalhe no Antigo Testamento. A partir daí, o texto é direto sobre o que se instala no coração de Esaú: "aborreceu" Jacó — o mesmo verbo hebraico usado para ódio profundo, não irritação passageira — e planeja secretamente: "achegar-se-ão os dias de luto de meu pai, e matarei a Jacó, meu irmão". Rebeca descobre o plano e manda Jacó fugir para a casa de seu tio Labão, numa separação que duraria mais de vinte anos.',
  biblico_aplicacao = 'O rancor de Esaú não explode instantaneamente — ele se instala, é racionalizado, e recebe um plano e um prazo ("depois que meu pai morrer"). Guardar mágoa em silêncio, esperando o momento certo de agir sobre ela, tende a fazê-la crescer, não diminuir, enquanto espera.',
  biblico_conexao = 'Hebreus 12:15 alerta especificamente sobre isso: cuidado para que não brote "alguma raiz de amargura" que "cause perturbação" e contamine muitos. Gênesis 33:1-4, décadas depois, mostra o reencontro surpreendente dos dois irmãos: Esaú corre ao encontro de Jacó, o abraça e chora — o rancor planejado nunca chegou a se concretizar em ação. Efésios 4:31-32 pede que se ponha fora "toda a amargura", substituindo-a por benignidade e perdão mútuo.'
where slug = 'rancor';

update public.feelings set
  biblico_nome = 'Saul contra Davi',
  biblico_referencia = '1 Samuel 18:6-16',
  biblico_versiculo = 'E irou-se Saul fortemente [...] e desde aquele dia em diante trazia Saul a Davi debaixo de olho.',
  biblico_teaser = 'Uma canção de comparação foi o suficiente pra transformar o rei que amava Davi num inimigo que passaria anos perseguindo-o.',
  biblico_contexto = 'Davi acabou de matar Golias e voltar vitorioso da batalha contra os filisteus. Ele já servia na corte de Saul, tocando harpa para acalmá-lo, e desenvolvera amizade próxima com o filho do rei, Jônatas.',
  biblico_capitulo = 'Quando o exército retorna, as mulheres saem cantando e dançando pelas cidades de Israel: "Saul feriu os seus milhares, porém Davi os seus dez milhares". A canção, provavelmente sem intenção maliciosa, acende algo em Saul: "desagradou isto muito a Saul, e o irritou este dito", e ele reflete: "a Davi deram dez milhares, e a mim [só] milhares; que mais lhe falta, senão o reino?" A partir desse dia, o texto marca uma virada permanente: "desde aquele dia em diante trazia Saul a Davi debaixo de olho" — vigilância constante nascida de comparação e insegurança, não de qualquer ação hostil real de Davi. No dia seguinte, um "espírito mau da parte de Deus" (permitido, segundo o texto, como consequência do afastamento de Saul) o agita, e enquanto Davi toca harpa como sempre fazia para acalmá-lo, Saul arremessa uma lança contra ele duas vezes, tentando encravá-lo na parede. Davi escapa nas duas ocasiões. O capítulo termina com Saul "tendo temor de Davi", porque reconhecia que "o Senhor era com ele, e se tinha retirado de Saul" — o ódio de Saul cresce precisamente na proporção em que ele reconhece o favor de Deus sobre Davi diminuindo o seu próprio.',
  biblico_aplicacao = 'O ódio de Saul nasce de comparação social e insegurança sobre a própria posição, não de qualquer traição real de Davi. Esse tipo de ódio, alimentado por medo de perder status, tende a se voltar contra a pessoa comparada mesmo quando ela não fez nada de errado — e no caso de Saul, o ódio perseguido por anos custou mais a ele mesmo do que a Davi.',
  biblico_conexao = '1 Samuel 24 e 26 mostram Davi poupando a vida de Saul duas vezes distintas, quando teve oportunidade e motivo de matá-lo — recusando responder ódio com ódio. Mateus 5:44 propõe o caminho oposto ao de Saul: "amai os vossos inimigos, bendizei os que vos maldizem". Provérbios 27:4 nomeia o parentesco entre os dois sentimentos: "cruel é o furor e a ira uma inundação; mas quem poderá resistir à inveja?".'
where slug = 'odio';

update public.feelings set
  biblico_nome = 'Os irmãos de José',
  biblico_referencia = 'Gênesis 37:3-11',
  biblico_versiculo = 'E seus irmãos o invejavam, mas seu pai guardava este negócio no seu coração.',
  biblico_teaser = 'A inveja cresceu de uma túnica pra dois sonhos, e dos sonhos direto para um plano de se livrar dele de vez.',
  biblico_contexto = 'José é o penúltimo filho de Jacó, mas o primeiro nascido de Raquel, a esposa mais amada. Jacó não esconde o favoritismo: presenteia José com uma túnica especial, e o texto é direto sobre o efeito disso nos outros filhos: "vendo, pois, seus irmãos que seu pai o amava mais do que a todos os seus irmãos, odiaram-no, e não podiam falar com ele pacificamente".',
  biblico_capitulo = 'A situação piora quando José, ainda jovem, relata dois sonhos aos irmãos: no primeiro, feixes de trigo dos irmãos se curvam diante do feixe dele; no segundo, o sol, a lua e onze estrelas se curvam diante dele — interpretado até pelo próprio pai como significando que toda a família, incluindo os pais, se prostraria diante de José. O texto marca com precisão a progressão emocional: primeiro "odiaram-no" por causa do favoritismo (v.4), depois "o invejaram ainda mais" especificamente por causa dos sonhos e das palavras dele (v.11) — inveja como uma camada adicional sobre o ódio já existente, ligada especificamente à possibilidade de José vir a ter autoridade sobre eles. É essa combinação de ódio antigo com inveja renovada que leva à decisão, poucos versículos depois, de vendê-lo como escravo. Curiosamente, o texto observa que Jacó, ao ouvir os sonhos, repreendeu José publicamente, mas "guardava este negócio no seu coração" — uma pista de que o próprio pai suspeitava de algo maior por trás daquelas palavras, mesmo sem conseguir prever o desfecho.',
  biblico_aplicacao = 'A inveja dos irmãos de José nasce de comparação direta — favoritismo visível, futuro anunciado de submissão a alguém mais jovem — e, não tratada, busca uma saída destrutiva. O texto não trata a inveja como sentimento neutro: ele a liga diretamente à decisão de vender o próprio irmão.',
  biblico_conexao = 'Tiago 3:14-16 nomeia o resultado prático da inveja não tratada: "perturbação e toda a obra perversa". Provérbios 14:30 contrasta: "o coração tranquilo é a vida da carne, mas a inveja é a podridão dos ossos". Gênesis 45:4-8, décadas depois, mostra José recontextualizando toda a história para os mesmos irmãos: "não vos entristeçais, nem vos pese aos vossos olhos [...] pois para conservação de vida Deus me enviou adiante de vós".'
where slug = 'inveja';

update public.feelings set
  biblico_nome = 'Raquel e Lia',
  biblico_referencia = 'Gênesis 29:31-30:24',
  biblico_versiculo = 'Vendo, pois, Raquel que não dava filhos a Jacó, teve Raquel ciúmes de sua irmã, e disse a Jacó: dá-me filhos, senão morro.',
  biblico_teaser = 'A irmã mais amada não conseguia engravidar, e a menos amada tinha filho atrás de filho — o ciúme nasceu direto dessa comparação.',
  biblico_contexto = 'Jacó ama Raquel, mas foi enganado por Labão, seu sogro, a se casar primeiro com Lia, a irmã mais velha, antes de finalmente também se casar com Raquel uma semana depois. As duas irmãs, ambas casadas com o mesmo homem, competem abertamente pelo afeto dele e pela fertilidade, num contexto cultural onde ter filhos determinava diretamente o valor e a segurança social de uma mulher.',
  biblico_capitulo = 'O texto é explícito sobre o mecanismo: "vendo, pois, o Senhor que Lia era desprezada, abriu a sua madre; Raquel, porém, era estéril" — Lia tem filho atrás de filho (Rúben, Simeão, Levi, Judá), cada nome carregando uma reflexão sobre a esperança de finalmente ser amada pelo marido através dos filhos ("agora amar-me-á meu marido", diz ela ao nomear Levi). Raquel, estéril e visivelmente amada por Jacó mas sem os filhos que dariam a ela segurança social, explode: "teve Raquel ciúmes de sua irmã, e disse a Jacó: dá-me filhos, senão morro" — cobrando do marido algo que não estava nas mãos dele resolver, e recebendo de volta uma resposta irritada: "acaso estou eu no lugar de Deus, que te impediu o fruto do ventre?" Raquel então dá sua serva Bila a Jacó como concubina, seguindo um costume da época, para "ter filhos por ela" — uma solução que gera mais filhos e mais competição entre as irmãs, incluindo uma disputa registrada em detalhe sobre mandrágoras (uma planta associada à fertilidade). O ciclo de comparação, filhos e competição atravessa quase dois capítulos inteiros antes de Raquel finalmente engravidar de José.',
  biblico_aplicacao = 'O ciúme de Raquel nasce de comparar sua própria falta (filhos) com a abundância visível da irmã, numa área da vida que genuinamente não estava sob seu controle. A cobrança dirigida a Jacó — "dá-me filhos, senão morro" — mostra como ciúme intenso pode levar a exigir de alguém algo que essa pessoa simplesmente não tem poder de resolver.',
  biblico_conexao = '1 Coríntios 13:4 descreve o oposto do ciúme como marca do amor genuíno: "o amor não é invejoso". Provérbios 14:30 já usado para inveja se aplica igualmente aqui: ciúme como "podridão dos ossos". Gênesis 30:22-24 mostra o desfecho: "lembrou-se Deus de Raquel [...] e abriu a sua madre", nascendo José — a resolução vindo no tempo de Deus, não no tempo da cobrança de Raquel.'
where slug = 'ciume';

update public.feelings set
  biblico_nome = 'O irmão mais velho do filho pródigo',
  biblico_referencia = 'Lucas 15:11-32',
  biblico_versiculo = 'Eis que te sirvo há tantos anos, sem nunca transgredir o teu mandamento, e nunca me deste um cabrito para eu me alegrar com os meus amigos.',
  biblico_teaser = 'Ele fez tudo certo por anos, sem festa nenhuma — e quando o irmão que errou tudo voltou, a casa inteira comemorou.',
  biblico_contexto = 'Jesus conta essa parábola, junto com a da ovelha perdida e da moeda perdida, em resposta direta a fariseus e escribas que murmuravam porque ele "recebe pecadores, e come com eles". A parábola tem três personagens centrais: o pai, o filho mais novo (que pede a herança antecipada, gasta tudo numa "vida dissoluta" e volta arruinado) e o filho mais velho, que ficou trabalhando em casa o tempo todo.',
  biblico_capitulo = 'Quando o filho mais novo volta, o pai o vê ainda de longe, corre ao encontro dele, o abraça, e organiza uma festa completa: o melhor vestido, um anel, calçado, e a matança do "bezerro cevado". O filho mais velho, voltando do campo, ouve música e dança de longe, e pergunta a um servo o que está acontecendo; ao saber que é uma festa pelo retorno do irmão, "indignou-se, e não queria entrar". O pai sai pessoalmente para convidá-lo — o mesmo gesto de iniciativa que teve com o filho mais novo — mas o filho mais velho responde com uma lista detalhada de queixas acumuladas: anos de serviço fiel, obediência total a cada mandamento, e nunca — nem um cabrito, o animal mais barato possível — recebido para celebrar com os próprios amigos. Ele nem chama o irmão de "meu irmão": refere-se a ele como "este teu filho", distanciando-se deliberadamente. O pai responde sem negar nem minimizar a fidelidade do filho mais velho: "filho, tu sempre estás comigo, e tudo o que é meu é teu. Mas era justo alegrar e folgar, porque este teu irmão estava morto, e reviveu; e tinha-se perdido, e foi achado." A parábola termina exatamente aí, sem revelar se o irmão mais velho finalmente entrou na festa.',
  biblico_aplicacao = 'O ressentimento do irmão mais velho é tratado pela parábola com seriedade, não como reação exagerada — o pai não o repreende por sentir isso, explica com paciência a lógica por trás da celebração. O final em aberto sugere que a decisão de deixar o ressentimento de lado, e entrar na festa, continua sendo uma escolha pessoal, não automática.',
  biblico_conexao = 'Gálatas 6:9 fala diretamente a quem faz o bem sem retorno visível: "não desanimemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido". Mateus 20:1-16, a parábola dos trabalhadores da vinha, traz o mesmo desconforto: todos pagos igualmente, independente da hora que começaram a trabalhar. Jonas 4, já visto em outro sentimento, mostra o mesmo tipo de indignação diante da graça estendida a quem "não merecia".'
where slug = 'ressentimento';

update public.feelings set
  biblico_nome = 'O servo que não perdoou',
  biblico_referencia = 'Mateus 18:21-35',
  biblico_versiculo = 'E, saindo aquele servo, encontrou um de seus conservos, que lhe devia cem dinheiros; e, lançando mão dele, sufocava-o, dizendo: paga-me o que me deves.',
  biblico_teaser = 'Ele acabou de ter uma dívida impagável perdoada — e minutos depois, sufocou um colega por uma dívida centenas de vezes menor.',
  biblico_contexto = 'Pedro pergunta a Jesus quantas vezes deveria perdoar um irmão que pecasse contra ele, sugerindo até sete vezes — já um número generoso para os padrões rabínicos da época, que geralmente limitavam o perdão a três vezes pela mesma ofensa. Jesus responde que não até sete, "mas até setenta vezes sete" — uma forma hebraica de dizer "sem limite contável" — e ilustra com uma parábola.',
  biblico_capitulo = 'Um rei decide acertar contas com seus servos, e um deles é trazido devendo dez mil talentos — uma quantia absurdamente alta, equivalente a mais de cento e cinquenta mil anos de salário de um trabalhador comum, uma dívida deliberadamente impossível de ser paga em qualquer cenário realista. O rei ordena que ele, sua esposa, filhos e tudo o que possui sejam vendidos para pagamento parcial. O servo se prostra implorando paciência, prometendo pagar tudo — uma promessa matematicamente impossível — e o rei, "movido de intima compaixão", não apenas concede prazo, mas perdoa a dívida inteira. Saindo dali, o mesmo servo encontra um colega que lhe devia cem dinheiros — uma quantia real, mas pequena, equivalente a cerca de cem dias de salário, uma fração ínfima do que acabara de ser perdoado a ele. Ele o agarra pela garganta exigindo pagamento imediato, ignora o mesmo pedido de paciência que ele próprio tinha feito ao rei, e o manda prender até pagar a dívida. Outros servos, testemunhando a cena, ficam "muito entristecidos" e relatam tudo ao rei, que chama o primeiro servo de volta: "servo malvado, toda aquela dívida te perdoei, porque me suplicaste. Não devias tu, também, ter compaixão do teu companheiro, como eu também tive compaixão de ti?" O rei entrega o servo aos verdugos até que pagasse tudo o que devia — uma dívida impagável, restaurada como sentença.',
  biblico_aplicacao = 'A parábola mede a falta de perdão pela desproporção entre o que foi perdoado a nós e o que nos recusamos a perdoar aos outros. A memória seletiva do primeiro servo — lembrar da dívida alheia e esquecer da própria, perdoada minutos antes — é exatamente o mecanismo que a parábola expõe como incoerência grave.',
  biblico_conexao = 'Mateus 6:12 já tinha ensinado essa conexão direta na oração do Pai Nosso: "perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores". Colossenses 3:13 pede o mesmo padrão: "assim como Cristo vos perdoou, assim fazei vós também". Efésios 4:32 conecta bondade, compaixão e perdão mútuo diretamente ao exemplo de Deus em Cristo.'
where slug = 'falta-de-perdao';

update public.feelings set
  biblico_nome = 'Pedro pergunta sobre João',
  biblico_referencia = 'João 21:15-22',
  biblico_versiculo = 'Vendo-o, pois, Pedro, disse a Jesus: Senhor, e este, que? Disse-lhe Jesus: [...] que te importa a ti? Segue-me tu.',
  biblico_teaser = 'No exato momento em que recebia sua própria missão de volta, Pedro já estava olhando pro lado, comparando com o destino de outro.',
  biblico_contexto = 'Jesus acabou de restaurar Pedro através de uma sequência de três perguntas ("tu me amas?"), espelhando as três negações da noite da prisão, e lhe devolveu uma missão concreta: "apascenta as minhas ovelhas". Ele também revela a Pedro, de forma velada, como este morreria — um martírio, segundo o texto, "para significar com que morte havia ele de glorificar a Deus".',
  biblico_capitulo = 'Imediatamente depois dessa revelação pessoal e pesada sobre o próprio destino, Pedro se vira e vê João ("o discípulo a quem Jesus amava") seguindo por perto, e pergunta sem rodeios: "Senhor, e este, que?" — literalmente, "e quanto a ele, o que vai acontecer?". A resposta de Jesus é direta, quase cortante: "se eu quero que ele fique até que eu venha, que te importa a ti? Segue-me tu." A frase é repetida — "segue-me tu" — reforçando o redirecionamento do foco de volta para Pedro e sua própria missão específica. O texto nota que essa resposta gerou um boato entre os irmãos de que João não morreria, e faz questão de corrigir o mal-entendido: Jesus não tinha dito que ele não morreria, só que a questão não era da conta de Pedro. O capítulo — e o evangelho inteiro — termina logo em seguida, sem mais desenvolvimento sobre a comparação entre os dois discípulos.',
  biblico_aplicacao = 'A pergunta de Pedro é humanamente compreensível — ele acabara de receber notícia difícil sobre o próprio futuro, e comparar com o de outra pessoa é quase automático nesse momento. A resposta de Jesus não repreende a curiosidade com dureza, mas corta a comparação pela raiz, devolvendo o foco exatamente para onde precisava estar: a missão pessoal de Pedro, não o destino alheio.',
  biblico_conexao = 'Gálatas 6:4-5 pede o mesmo foco: "prove cada um a sua própria obra [...] porque cada qual levará o seu próprio fardo". 2 Coríntios 10:12 adverte contra "comparar-se consigo mesmos" como medida de valor. Romanos 14:4 pergunta diretamente: "quem és tu, que julgas o servo alheio?" — a mesma redireção de foco que Jesus deu a Pedro.'
where slug = 'comparacao';

update public.feelings set
  biblico_nome = 'Os pescadores sem nada a noite toda',
  biblico_referencia = 'Lucas 5:1-11',
  biblico_versiculo = 'Mestre, havendo trabalhado toda a noite, nada apanhamos; mas, sobre a tua palavra, lançarei a rede.',
  biblico_teaser = 'Uma noite inteira de trabalho profissional, e nada — até serem mandados fazer, em pleno dia, o que já parecia inútil tentar de novo.',
  biblico_contexto = 'Jesus está ensinando à beira do lago de Genesaré (mar da Galileia), com a multidão o pressionando tanto que ele pede emprestado o barco de Simão Pedro, ainda um pescador comum na época, para se afastar um pouco da margem e continuar ensinando dali.',
  biblico_capitulo = 'Depois de terminar de ensinar, Jesus se dirige diretamente a Simão: "faze-te ao largo, e lançai as vossas redes para pescar." Simão responde com a frustração legítima de um profissional experiente: "Mestre, havendo trabalhado toda a noite, nada apanhamos." A pesca na região era tradicionalmente feita à noite, quando os peixes se aproximavam da superfície; pescar de dia, especialmente depois de uma noite inteira sem resultado, contrariava tanto a experiência prática quanto a lógica. Ainda assim, Simão completa a frase com uma decisão notável: "mas, sobre a tua palavra, lançarei a rede." O resultado é uma pesca tão grande que a rede começa a se romper, e eles precisam chamar os sócios do outro barco (Tiago e João) para ajudar a recolher — os dois barcos ficam tão cheios que quase afundam. A reação de Simão não é celebração imediata: ele se lança aos pés de Jesus e diz "retira-te de mim, Senhor, porque sou um homem pecador", tomado de espanto. Jesus responde com o chamado que definiria o resto de sua vida: "não temas; desde agora serás pescador de homens." O texto conclui que, ao chegarem à terra, "deixando tudo, o seguiram."',
  biblico_aplicacao = 'A frustração de Simão diante de uma noite inteira de esforço sem resultado é tratada com respeito — ele não é repreendido por mencioná-la. Mas ele escolhe obedecer apesar da frustração e da lógica contrária, e é exatamente esse ato de confiança em cima de um fracasso recente que abre espaço para a maior pesca de sua vida, seguida por um chamado que muda tudo.',
  biblico_conexao = 'Gálatas 6:9 promete colheita no tempo certo, "se não houvermos desfalecido". João 21:1-6, já visto em outro sentimento, repete quase a mesma estrutura no fim do ministério de Pedro: noite sem nada, instrução de Jesus, rede cheia. Salmos 127:1-2 lembra que esforço sem direção certa "em vão trabalham os que a edificam".'
where slug = 'frustracao';

update public.feelings set
  biblico_nome = 'Jonas debaixo da planta',
  biblico_referencia = 'Jonas 4:1-11',
  biblico_versiculo = 'Agora pois, ó Senhor, peço-te que me tires a vida, porque melhor me é morrer do que viver.',
  biblico_teaser = 'Ele acabou de completar a maior missão da própria vida — e ainda assim pediu pra morrer, perdendo de vista o propósito que tinha acabado de cumprir.',
  biblico_contexto = 'Jonas finalmente obedece à ordem de pregar arrependimento a Nínive, capital do império assírio, inimigo histórico e violento de Israel, depois de tentar fugir na direção oposta e passar três dias dentro de um grande peixe. A pregação funciona além do esperado: a cidade inteira, do rei ao gado, se arrepende, e Deus decide não destruí-la.',
  biblico_capitulo = 'Em vez de celebrar o sucesso da própria missão, o texto diz que "isto pareceu mal a Jonas, e ficou muito irado" — ele reclama diretamente a Deus, revelando o motivo real de sua fuga original: "não foi este o meu dito, quando ainda estava na minha terra? Por isso me apressei a fugir para Társis; porque sabia que tu és Deus clemente e misericordioso [...] e que te arrependes do mal." Jonas sabia, desde o início, que Deus provavelmente perdoaria a cidade — e essa certeza é exatamente o que o fazia não querer ir. Ele pede para morrer, sai da cidade e constrói uma cabana, sentando-se "à sombra, até ver o que seria da cidade." Deus faz crescer uma planta (provavelmente uma mamoneira) que dá sombra a Jonas, e ele "se alegrou muito por causa da plantinha." No dia seguinte, porém, um verme ataca a planta e ela seca; combinado com um vento oriental quente, Jonas desmaia de calor e pede para morrer pela segunda vez no mesmo capítulo — agora não pela cidade perdoada, mas por causa de uma única planta perdida. Deus então faz a pergunta central do livro, contrastando as prioridades de Jonas: se ele tem pena de uma planta que não plantou nem cultivou, que "numa noite nasceu, e numa noite pereceu", por que Deus não teria pena de Nínive, "que tem mais de cento e vinte mil pessoas"? O livro termina exatamente nessa pergunta, sem resposta registrada de Jonas.',
  biblico_aplicacao = 'A crise de propósito de Jonas surge logo depois do maior sucesso de sua missão, quando um detalhe pequeno (a planta) ofusca completamente a visão do que tinha sido realizado em grande escala. Perder de vista o propósito cumprido, distraído por uma perda menor, é um padrão que a Bíblia registra sem disfarçar como falha de perspectiva, não como acusação moral.',
  biblico_conexao = 'Efésios 2:10 lembra o propósito que continua ativo mesmo quando não se sente: "somos feitura sua, criados [...] para boas obras, as quais Deus preparou de antemão". Eclesiastes 3:11 fala de Deus tendo posto "a eternidade no coração do homem" — uma inquietação por sentido maior que nenhuma planta, sozinha, resolve. 1 Reis 19:4, já visto no sentimento de esgotamento, mostra Elias fazendo o mesmo pedido de morte, também depois de uma vitória, também sob uma árvore.'
where slug = 'falta-de-proposito';

update public.feelings set
  biblico_nome = 'Félix adia a decisão',
  biblico_referencia = 'Atos 24:22-27',
  biblico_versiculo = 'E, tratando ele do juízo, da temperança e do juízo vindouro, Félix ficou aterrorizado, e respondeu: por agora vai-te, e, quando tiver ocasião oportuna, te chamarei.',
  biblico_teaser = 'Ele ficou visivelmente perturbado com o que ouviu — e escolheu adiar a resposta indefinidamente, esperando um momento que nunca chegou.',
  biblico_contexto = 'Paulo é levado preso a Cesareia, acusado por líderes judaicos diante do governador romano Félix. Depois de ouvir as acusações e a defesa de Paulo, Félix, que já tinha "mais exato conhecimento deste Caminho" (o cristianismo), adia o julgamento formal, mas mantém Paulo sob custódia relativamente branda, permitindo visitas de amigos.',
  biblico_capitulo = 'Alguns dias depois, Félix retorna acompanhado de sua esposa Drusila, "que era judia", e manda chamar Paulo especificamente para ouvi-lo falar sobre "a fé em Cristo". Paulo não suaviza a mensagem para agradar o poderoso casal: fala "acerca da justiça, e da temperança, e do juízo vindouro" — temas desconfortáveis para um governador conhecido por corrupção e abuso de poder. O texto registra a reação física de Félix: ele "ficou aterrorizado" (grego emphobos genomenos, "tomado de medo/tremor"). Em vez de responder à convicção que sentia, ele interrompe a conversa: "por agora vai-te; e, quando tiver ocasião oportuna, te chamarei." O texto acrescenta um detalhe revelador sobre o motivo real por trás dos encontros seguintes: "esperava também que Paulo lhe desse dinheiro, para o soltar; por isso o mandava chamar muitas vezes, e falava com ele." Félix mantém Paulo preso por dois anos inteiros sem resolver o caso, até ser substituído por outro governador, Pórcio Festo — a "ocasião oportuna" que ele prometeu nunca chega a se concretizar durante todo o seu governo.',
  biblico_aplicacao = 'A procrastinação de Félix não nasce de indiferença — nasce de convicção real, forte o suficiente para causar terror físico, mas administrada por adiamento em vez de resposta. A "ocasião oportuna" que ele esperava era, na prática, uma forma de nunca precisar decidir — e o texto marca que ela nunca chegou por conta própria.',
  biblico_conexao = '2 Coríntios 6:2 aponta pro oposto dessa procrastinação: "eis aqui agora o tempo aceitável, eis aqui agora o dia da salvação". Hebreus 3:15 repete um alerta do Salmo 95: "se ouvirdes hoje a sua voz, não endureçais os vossos corações". Provérbios 27:1 adverte sobre depender do amanhã: "não te glories do dia de amanhã, porque não sabes o que produzirá o dia".'
where slug = 'procrastinacao';

update public.feelings set
  biblico_nome = 'O preguiçoso de Provérbios',
  biblico_referencia = 'Provérbios 6:6-11 e 24:30-34',
  biblico_versiculo = 'Vai-te à formiga, ó preguiçoso, considera os seus caminhos, e sê sábio; a qual, não tendo superior, nem oficial, nem dominador, no verão prepara a sua comida.',
  biblico_teaser = 'A formiga não tem chefe, supervisor nem prazo imposto — e ainda assim se organiza sozinha. É esse o espelho oferecido ao preguiçoso.',
  biblico_contexto = 'Provérbios é uma coleção de ditos de sabedoria prática voltada à formação de caráter no cotidiano, atribuída majoritariamente a Salomão, endereçada especificamente a "meu filho" ao longo do livro — um pai instruindo um jovem sobre as consequências reais de escolhas pequenas e repetidas.',
  biblico_capitulo = 'O capítulo 6 usa a formiga como contra-exemplo direto: ela trabalha "não tendo superior, nem oficial, nem dominador" — nenhuma estrutura de cobrança externa — e ainda assim "no verão prepara a sua comida, e ajunta o seu mantimento na sega", agindo por iniciativa própria diante de uma estação que ela sabe que vai acabar. A pergunta que segue é direta: "até quando, ó preguiçoso, ficarás deitado? Quando te levantarás do teu sono?" O texto descreve o ciclo específico da procrastinação disfarçada de descanso: "um pouco de sono, adormecendo um pouco; um pouco de cruzar as mãos, deitado" — cada "um pouco" parecendo inofensivo isoladamente, mas somando-se a um padrão. A consequência é descrita com duas imagens de chegada inevitável e repentina: "a tua pobreza virá como o caminhante, e a tua necessidade como um homem armado" — não uma punição arbitrária, uma consequência natural que chega sem avisar quando menos se espera. Provérbios 24:30-34 repete quase as mesmas palavras sobre pobreza chegando "como o caminhante", desta vez ilustrado com a observação direta do autor passando por um campo de um homem preguiçoso, "tudo cheio de espinhos", o muro de pedra já caído — evidência visível e acumulada de negligência repetida ao longo do tempo, não de um único dia ruim.',
  biblico_aplicacao = 'A formiga age por convicção própria da estação, sem ninguém cobrando — o oposto do padrão descrito no preguiçoso, que precisa ser questionado diretamente ("até quando?") porque não tem esse motor interno ativado. O texto não trata preguiça como incapacidade, trata como um padrão de pequenas escolhas repetidas, cada uma parecendo inofensiva isoladamente.',
  biblico_conexao = 'Gálatas 6:9 dá o outro lado da mesma moeda: não desanimar de fazer o bem, porque "a seu tempo ceifaremos, se não houvermos desfalecido". Eclesiastes 9:10 recomenda fazer "com a tua força" tudo o que a mão encontrar para fazer. 2 Tessalonicenses 3:10 registra um princípio prático da igreja primitiva: "se alguém não quer trabalhar, também não coma".'
where slug = 'preguica';

update public.feelings set
  biblico_nome = 'Saul oferece o sacrifício sem esperar',
  biblico_referencia = '1 Samuel 13:5-14',
  biblico_versiculo = 'E Saul disse: Trazei-me aqui um holocausto, e ofertas pacíficas. E ofereceu o holocausto. [...] E eis que veio Samuel.',
  biblico_teaser = 'Ele esperou quase até o fim do prazo — e no último momento, decidiu fazer sozinho o que devia esperar outra pessoa fazer.',
  biblico_contexto = 'Saul, já rei de Israel, enfrenta um exército filisteu descrito como "em multidão como a areia que está à borda do mar", enquanto seu próprio exército começa a se dispersar de medo, os homens se escondendo em covas, fendas e cisternas. O profeta Samuel tinha instruído Saul a esperar sete dias em Gilgal até sua chegada, para oferecer sacrifício antes da batalha.',
  biblico_capitulo = 'O texto marca o tempo com precisão: "e esperou sete dias, até ao tempo que Samuel tinha determinado; não vindo, porém, Samuel a Gilgal, o povo se derramava de detrás dele." É especificamente no limite do prazo combinado, vendo o próprio exército se dissolver, que Saul toma a decisão: "trazei-me aqui um holocausto" — uma função sacerdotal que não lhe cabia, reservada a Samuel. Ele mesmo oferece o sacrifício, e "eis que, acabando ele de oferecer o holocausto, eis que Samuel chegou" — a demora tinha um prazo real, e Saul agiu exatamente antes dele se cumprir. Samuel confronta Saul diretamente: "que fizeste?" Saul se justifica com uma lista de pressões reais — o povo se dispersando, os filisteus se ajuntando, a falta de tempo para buscar o favor do Senhor — concluindo: "me constrangi, e ofereci holocausto." A resposta de Samuel é severa e tem consequência dinástica permanente: "agiste nesciamente [...] agora não subsistirá o teu reino; já tem buscado o Senhor para si um homem segundo o seu coração" — uma referência direta a Davi, ainda não introduzido na narrativa, mas já designado como consequência dessa impaciência específica de Saul.',
  biblico_aplicacao = 'A impaciência de Saul nasce de pressão circunstancial real — não é capricho, é medo genuíno de perder a batalha e o exército. Ainda assim, o texto trata a decisão de ocupar um papel que não era seu, só para não esperar mais, como erro grave o suficiente para custar a continuidade de seu próprio reinado.',
  biblico_conexao = 'Salmos 27:14 recomenda o oposto: "espera no Senhor, anima-te, e ele fortalecerá o teu coração; espera, pois, no Senhor." Isaías 40:31 promete que "os que esperam no Senhor renovarão as forças". Hebreus 6:12 recomenda ser "imitadores dos que pela fé e paciência herdam as promessas" — a combinação específica de fé com paciência, não fé sozinha.'
where slug = 'impaciencia';

update public.feelings set
  biblico_nome = 'A restauração de Pedro',
  biblico_referencia = 'João 21:15-19',
  biblico_versiculo = 'Simão, filho de Jonas, amas-me mais do que estes? [...] Disse-lhe: apascenta os meus cordeiros.',
  biblico_teaser = 'Ele tinha negado conhecer Jesus três vezes — e a restauração veio em exatamente três perguntas, sem exigir explicação nenhuma.',
  biblico_contexto = 'Depois da pesca miraculosa e do café da manhã na praia (João 21:1-14), Jesus se dirige diretamente a Simão Pedro, que semanas antes tinha negado conhecê-lo três vezes na noite da prisão, chorando amargamente depois de perceber o que tinha feito (Mateus 26:75).',
  biblico_capitulo = 'Jesus pergunta três vezes seguidas, com pequenas variações: "Simão, filho de Jonas, amas-me mais do que estes?", depois "amas-me?", depois pela terceira vez a mesma pergunta — o número exato de vezes que Pedro tinha negado conhecê-lo. O texto registra que Pedro "entristeceu-se" com a terceira repetição, provavelmente reconhecendo o eco intencional das três negações. Cada resposta afirmativa de Pedro ("Senhor, tu sabes todas as coisas; tu sabes que eu te amo") recebe de volta uma missão concreta e crescente: "apascenta os meus cordeiros", "apascenta as minhas ovelhas", "apascenta as minhas ovelhas" — a mesma vocação de cuidado pastoral repetida três vezes, tantas quantas foram as negações. Em nenhum momento Jesus exige que Pedro explique ou se desculpe formalmente pela negação; a restauração acontece através de uma pergunta sobre amor presente, não sobre a falha passada. Jesus então revela a Pedro, de forma velada, como ele morreria — um martírio que glorificaria a Deus — e encerra com o mesmo convite que deu no início, anos antes, à beira do mesmo mar: "segue-me."',
  biblico_aplicacao = 'Recomeçar depois de uma queda grave, no exemplo de Pedro, não exige apagar a memória do que aconteceu nem provar mérito suficiente para merecer confiança de volta. A restauração vem através de uma pergunta simples repetida com intenção — não sobre capacidade, sobre amor — e devolve a mesma missão de antes, sem diminuí-la por causa da queda.',
  biblico_conexao = 'Lucas 22:31-32 mostra Jesus já orando por essa restauração antes mesmo da negação acontecer: "eu roguei por ti, para que a tua fé não desfaleça [...] e, quando te converteres, confirma teus irmãos". Lamentações 3:22-23 fala de misericórdias "que se renovam cada manhã". Isaías 43:18-19 promete: "não vos lembreis das coisas passadas [...] eis que faço uma coisa nova".'
where slug = 'dificuldade-de-recomecar';

update public.feelings set
  biblico_nome = 'Jesus tentado no deserto',
  biblico_referencia = 'Mateus 4:1-11',
  biblico_versiculo = 'E, aproximando-se dele o tentador, disse: Se tu és Filho de Deus, dize que estas pedras se tornem em pães.',
  biblico_teaser = 'Cada tentação oferecia algo legítimo — comida, proteção, poder — só que no momento errado e pelo caminho errado.',
  biblico_contexto = 'Imediatamente depois de ser batizado por João Batista, momento em que uma voz do céu o declara "Filho amado", Jesus é levado pelo Espírito ao deserto especificamente para ser tentado pelo diabo, depois de jejuar quarenta dias e quarenta noites, "depois teve fome".',
  biblico_capitulo = 'A primeira tentação explora exatamente a fome real de Jesus: "se tu és Filho de Deus, dize que estas pedras se tornem em pães" — um desafio embutido de prova de identidade, e uma solução legítima (comida) oferecida no momento e forma errados. Jesus responde citando Deuteronômio 8:3: "nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus." Na segunda tentação, o diabo o leva ao pináculo do templo e propõe que se jogue, citando o próprio Salmo 91 ("aos seus anjos dará ordens a teu respeito [...] para que nunca tropeces em alguma pedra") — uma tentação de testar Deus publicamente, usando Escritura fora de contexto para justificar o teste. Jesus responde com outra citação de Deuteronômio: "não tentarás o Senhor teu Deus." Na terceira, o diabo mostra a Jesus "todos os reinos do mundo, e a glória deles", oferecendo tudo isso em troca de um único ato de adoração — poder legítimo, prometido de qualquer forma a Jesus segundo outras passagens proféticas, mas oferecido pelo caminho errado, sem a cruz. Jesus responde pela terceira vez com Deuteronômio: "ao Senhor teu Deus adorarás, e só a ele servirás", e ordena que o diabo se retire. O capítulo termina com anjos vindo servi-lo — provisão chegando logo depois da resistência, não antes dela.',
  biblico_aplicacao = 'Nenhuma das três tentações oferece algo intrinsecamente mau — comida, segurança, poder são todos legítimos em si. O padrão comum é a proposta de obtê-los pelo caminho errado, no momento errado, fora da forma que Deus já tinha estabelecido. Reconhecer essa diferença — não é sobre o que está sendo oferecido, é sobre o caminho até ele — é o que sustenta cada resposta de Jesus.',
  biblico_conexao = '1 Coríntios 10:13 garante que toda tentação vem com uma saída, "para que a possais suportar". Hebreus 4:15 lembra que Jesus "foi tentado em tudo, à nossa semelhança, mas sem pecado" — tornando sua compreensão da tentação humana real, não teórica. Tiago 1:13-15 esclarece que Deus não tenta ninguém ao mal; a tentação nasce da própria concupiscência, que "tendo concebido, dá à luz o pecado".'
where slug = 'tentacao';

update public.feelings set
  biblico_nome = 'Davi confrontado por Natã',
  biblico_referencia = '2 Samuel 11:1-12:13',
  biblico_versiculo = 'Então disse Davi a Natã: Pequei contra o Senhor. E disse Natã a Davi: também o Senhor traspassou o teu pecado; não morrerás.',
  biblico_teaser = 'Ele cometeu adultério, tentou encobrir e mandou matar um homem inocente — e quando confrontado, não se defendeu nem uma palavra.',
  biblico_contexto = 'Numa época em que "os reis costumavam sair à guerra", Davi permanece em Jerusalém em vez de liderar o exército, e avista Bate-Seba, esposa de Urias (um de seus soldados de elite), tomando banho. Ele a manda chamar, comete adultério com ela, e ela engravida.',
  biblico_capitulo = 'Davi tenta encobrir o próprio pecado chamando Urias de volta da guerra, esperando que ele durma com a esposa e a gravidez pareça legítima — mas Urias, num gesto de lealdade que contrasta diretamente com a conduta de Davi, se recusa a ir para casa enquanto seus companheiros ainda estão acampados em batalha. Diante do plano frustrado, Davi escala a gravidade da própria ação: manda uma carta a Joabe, seu general, instruindo-o a posicionar Urias na linha de frente mais perigosa e depois recuar o apoio, garantindo sua morte em combate — Urias literalmente carrega até a própria sentença de morte, sem saber. Depois do luto formal, Davi toma Bate-Seba como esposa. O texto fecha o capítulo com uma frase curta e definitiva: "mas o que Davi fizera pareceu mal aos olhos do Senhor." No capítulo seguinte, o profeta Natã é enviado, e conta uma parábola sobre um homem rico com muitos rebanhos que, para hospedar um viajante, rouba e mata a única ovelha de um vizinho pobre. Davi se indigna genuinamente com a injustiça da história e declara que o homem rico merece morte. Natã responde com quatro palavras que viram o quadro completamente: "tu és este homem." Ele detalha, um por um, todos os benefícios que Davi já tinha recebido de Deus, e a gravidade do que fez em troca. A resposta de Davi não inclui nenhuma defesa, negociação ou justificativa: "pequei contra o Senhor." Cinco palavras, sem rodeio. Natã responde imediatamente que o pecado foi perdoado, embora consequências graves ainda viessem a acontecer na família de Davi.',
  biblico_aplicacao = 'A confissão de Davi é notável pela ausência total de defesa ou minimização — nenhuma menção a atenuantes, nenhuma tentativa de recontextualizar o próprio comportamento. É essa confissão direta e sem rodeio, não um processo longo de justificativa, que abre espaço para o perdão declarado por Natã na sequência imediata.',
  biblico_conexao = 'Salmos 51, tradicionalmente atribuído a Davi como resposta a esse exato confronto, é um dos textos de arrependimento mais crus da Bíblia: "contra ti, contra ti somente, pequei". 1 João 1:9 promete o mesmo padrão de perdão: "se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar". Provérbios 28:13 contrasta encobrir pecado com confessá-lo e deixá-lo: só o segundo caminho "alcançará misericórdia".'
where slug = 'culpa';

update public.feelings set
  biblico_nome = 'Adão e Eva se escondem',
  biblico_referencia = 'Gênesis 3:1-13',
  biblico_versiculo = 'E abriram-se os olhos de ambos, e conheceram que estavam nus [...] e esconderam-se da presença do Senhor Deus.',
  biblico_teaser = 'A primeira reação registrada depois do primeiro erro humano não foi confissão — foi se cobrir e se esconder.',
  biblico_contexto = 'No jardim do Éden, Deus tinha dado uma única restrição a Adão e Eva: não comer do fruto da árvore do conhecimento do bem e do mal. A serpente convence Eva de que comer traria conhecimento igual ao de Deus, sem consequência real — contradizendo diretamente o aviso original.',
  biblico_capitulo = 'Depois de ambos comerem o fruto, a primeira mudança registrada não é física nem punitiva — é perceptiva: "abriram-se os olhos de ambos, e conheceram que estavam nus", e a primeira ação é costurar folhas de figueira para se cobrirem, uma resposta improvisada e claramente insuficiente à vergonha recém-descoberta. Quando ouvem "a voz do Senhor Deus, que passeava no jardim pela viração do dia", a reação é imediata: "escondeu-se Adão e sua mulher da presença do Senhor Deus, por entre as árvores do jardim." A pergunta de Deus que segue — "onde estás?" — não busca informação (Deus obviamente sabia onde eles estavam fisicamente); é uma abertura de conversa que a vergonha tinha fechado, um convite implícito a sair do esconderijo. Adão responde admitindo o medo e a nudez como motivo de se esconder, e quando questionado diretamente se comeu da árvore proibida, começa uma cadeia de transferência de culpa: Adão culpa Eva (e indiretamente o próprio Deus, "a mulher que me deste por companheira"), Eva culpa a serpente. Apesar da vergonha, do esconderijo e da tentativa de transferir responsabilidade, Deus continua a conversa, pronuncia consequências, mas termina o capítulo com um gesto de cuidado prático: "fez também o Senhor Deus túnicas de peles, e vestiu-os" — uma cobertura mais adequada, feita pelo próprio Deus, substituindo as folhas de figueira improvisadas.',
  biblico_aplicacao = 'A vergonha empurra para o esconderijo, exatamente na direção oposta da presença que continua procurando por quem se escondeu. A pergunta "onde estás?" não é acusação — é o primeiro movimento de busca registrado na Bíblia, e vem antes de qualquer julgamento sobre o que foi feito.',
  biblico_conexao = 'Salmos 34:5 promete o oposto do rosto escondido: "olharam para ele, e se alegraram; e os seus rostos não foram confundidos." Hebreus 4:16 convida a se aproximar "com confiança do trono da graça", em vez de se esconder dele. Romanos 8:1 declara que "nenhuma condenação há para os que estão em Cristo Jesus" — a cobertura que as túnicas de pele no Éden já anunciavam de forma provisória.'
where slug = 'vergonha';

update public.feelings set
  biblico_nome = 'Moisés diante do chamado',
  biblico_referencia = 'Êxodo 3:1-4:17',
  biblico_versiculo = 'Então disse Moisés a Deus: Quem sou eu, para que vá a Faraó, e tire do Egito os filhos de Israel?',
  biblico_teaser = 'Ele questionou a própria capacidade repetidas vezes — e cada objeção recebeu uma resposta específica, sem que o chamado fosse cancelado.',
  biblico_contexto = 'Moisés vive exilado no deserto de Midiã há quarenta anos, cuidando das ovelhas do sogro, depois de fugir do Egito por ter matado um capataz egípcio décadas antes. Ele já não é o príncipe criado na corte do Faraó — é um pastor comum, esquecido, quando avista uma sarça que queima sem se consumir.',
  biblico_capitulo = 'Deus se revela na sarça e anuncia a Moisés a missão: libertar o povo de Israel da escravidão no Egito. A resposta de Moisés é uma sequência de objeções, cada uma tratada com seriedade por Deus, não descartada: primeiro, "quem sou eu, para que vá a Faraó?" — questionando a própria adequação para a tarefa; Deus responde não validando as qualificações de Moisés, mas prometendo presença: "certamente eu serei contigo." Segundo, Moisés pergunta que nome de Deus deveria dizer ao povo, recebendo a revelação central "Eu Sou o que Sou". Terceiro, ele antecipa que não vão acreditar nele, e Deus dá sinais visíveis — a vara que vira serpente, a mão que fica leprosa e depois normal — como prova concreta. Quarto, Moisés declara diretamente sua limitação de fala: "eu não sou eloquente [...] sou pesado de boca e pesado de língua", ao que Deus responde perguntando quem fez a boca do homem, e promete estar com sua boca e ensiná-lo o que dizer. Mesmo depois de toda essa sequência de respostas específicas para cada insegurança levantada, Moisés faz um último pedido, mais direto: "ah, Senhor! envia por mão daquele a quem tu hás de enviar" — essencialmente, "manda outra pessoa". É a única vez no capítulo em que o texto registra a ira de Deus se acendendo contra Moisés — não pelas objeções anteriores, tratadas uma a uma com paciência, mas por essa recusa final depois de já ter recebido toda resposta necessária. Mesmo assim, Deus não cancela o chamado: designa Arão, irmão de Moisés, para falar por ele, ajustando o plano sem abandoná-lo.',
  biblico_aplicacao = 'Cada insegurança específica de Moisés recebe uma resposta específica de Deus — presença, identidade, sinais, capacidade de fala — sem que o chamado seja retirado por causa delas. A insegurança não invalida a missão; ela apenas revela onde exatamente é preciso de mais apoio para cumpri-la.',
  biblico_conexao = '2 Coríntios 3:5 tira o peso da capacidade própria: "não que sejamos capazes [...] mas a nossa capacidade vem de Deus". Juízes 6:15-16, o chamado de Gideão, segue um padrão quase idêntico de objeção seguida de reafirmação da presença de Deus. Jeremias 1:6-8 mostra outro chamado com a mesma estrutura: "não sei falar, porque sou moço" respondido com "eu sou contigo, para te livrar".'
where slug = 'inseguranca';

update public.feelings set
  biblico_nome = 'Paulo, o fariseu irrepreensível',
  biblico_referencia = 'Filipenses 3:4-14',
  biblico_versiculo = 'Quanto à justiça que há na lei, irrepreensível. Mas as coisas que para mim eram ganhos, considerei-as como perda por amor de Cristo.',
  biblico_teaser = 'Ele tinha o currículo religioso mais impecável possível pelos próprios padrões — e chamou tudo isso de lixo depois de encontrar algo maior.',
  biblico_contexto = 'Paulo (então Saulo) descreve sua trajetória antes da conversão como fariseu — o grupo religioso judaico mais rigoroso na observância detalhada da lei — perseguindo ativamente a igreja cristã por convicção de que estava defendendo a fé correta.',
  biblico_capitulo = 'Escrevendo aos filipenses, Paulo lista suas credenciais com precisão quase burocrática: circuncidado no oitavo dia (conforme exigido pela lei), da linhagem de Israel, da tribo de Benjamim, "hebreu de hebreus"; quanto à lei, fariseu; quanto ao zelo, perseguidor da igreja; quanto à justiça que há na lei, "irrepreensível" — um desempenho impecável medido pelos próprios critérios religiosos disponíveis, sem nenhuma falha visível registrada. Depois de listar tudo isso, ele faz uma virada radical: "mas as coisas que para mim eram ganhos, considerei-as como perda por amor de Cristo. E, na verdade, tenho também por perda todas as coisas [...] e as considero como esterco" — a palavra grega skybala, traduzida "esterco" ou "lixo", é um termo forte, praticamente vulgar no grego coloquial, usado deliberadamente para deixar claro o tamanho da reavaliação. Ele explica o motivo: não uma justiça própria, resultante da lei, mas "a que é pela fé de Cristo, a saber, a justiça que é de Deus pela fé". O capítulo termina com Paulo se descrevendo não como alguém que já chegou à perfeição, mas "prosseguindo para o alvo", esquecendo-se "das coisas que atrás ficam" — inclusive, implicitamente, o próprio histórico impecável que ele passara a vida construindo.',
  biblico_aplicacao = 'Uma vida de desempenho religioso perfeito, medida pelos próprios critérios, ainda deixou Paulo vazio o suficiente para chamá-la de lixo depois de encontrar algo que ele considerou maior. Perfeição de performance nunca foi o ponto central da mensagem que ele passou a pregar — e essa reavaliação vem de alguém que genuinamente tinha alcançado o padrão mais alto disponível.',
  biblico_conexao = '2 Coríntios 12:9 troca o padrão de perfeição por outro completamente diferente: "a minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza". Efésios 2:8-9 esclarece a base da nova justiça de Paulo: "pela graça sois salvos [...] não vem das obras, para que ninguém se glorie". Romanos 7:18-19 mostra Paulo, já apóstolo, ainda admitindo a distância entre o que quer fazer e o que consegue: "o querer o bem está em mim, mas não consigo levá-lo a efeito".'
where slug = 'perfeccionismo';

update public.feelings set
  biblico_nome = 'Nabucodonosor humilhado',
  biblico_referencia = 'Daniel 4:28-37',
  biblico_versiculo = 'Não é esta a grande Babilônia que eu edifiquei [...] pela força do meu poder, e para glória da minha majestade? [...] Naquela mesma hora se cumpriu a palavra sobre Nabucodonosor.',
  biblico_teaser = 'A frase de orgulho nem tinha terminado de ecoar, e uma sentença já estava caindo sobre quem a disse.',
  biblico_contexto = 'Nabucodonosor, rei da Babilônia, o império mais poderoso da época, já tinha tido um sonho perturbador interpretado por Daniel um ano antes, avisando especificamente sobre uma queda vindoura ligada ao próprio orgulho — um alerta que ele ouviu, mas cuja urgência parece ter se dissipado com o tempo.',
  biblico_capitulo = 'Exatamente doze meses depois do aviso, Nabucodonosor caminha pelo terraço do palácio real e declara, olhando para a cidade construída sob seu governo: "não é esta a grande Babilônia que eu edifiquei, para casa real, com a força do meu poder, e para glória da minha majestade?" — atribuindo toda a grandeza do império exclusivamente à própria capacidade, sem nenhuma menção a qualquer fonte além de si mesmo. O texto marca a velocidade da resposta: "estando ainda a palavra na boca do rei, caiu uma voz do céu", anunciando que o reino lhe seria tirado, que ele viveria "com os animais do campo" até reconhecer "que o Altíssimo tem domínio sobre o reino dos homens, e o dá a quem quer". A sentença se cumpre imediatamente: Nabucodonosor é "lançado dentre os filhos dos homens", come erva como os bois, seu corpo se molha com o orvalho do céu, seus cabelos crescem como penas de águia e suas unhas como garras de aves — uma descrição condizente com boantropia, uma condição psiquiátrica rara documentada na literatura médica, em que a pessoa acredita ser um animal. Depois do tempo determinado, o texto registra a restauração: "ao fim daqueles dias, eu, Nabucodonosor, levantei os meus olhos ao céu, e voltou a mim o meu entendimento", e ele mesmo escreve, em primeira pessoa, um louvor reconhecendo que "todas as suas obras são verdade [...] e ele é poderoso para humilhar os que andam na soberba".',
  biblico_aplicacao = 'O orgulho de Nabucodonosor não é apenas satisfação por uma conquista real — é a atribuição exclusiva dessa conquista a si mesmo, sem espaço para qualquer fonte além da própria força. O relato registra tanto a velocidade da consequência quanto a possibilidade real de restauração completa, incluindo o próprio testemunho do rei sobre o que aprendeu.',
  biblico_conexao = 'Provérbios 16:18 resume o padrão: "antes da destruição vem a soberba, e antes da queda, o espírito altivo". Tiago 4:6 confirma o padrão oposto: "Deus resiste aos soberbos, mas dá graça aos humildes". Isaías 14:12-15, sobre a queda do rei da Babilônia (numa geração posterior), usa linguagem semelhante sobre ambição de subir "acima das estrelas de Deus".'
where slug = 'orgulho';

update public.feelings set
  biblico_nome = 'Elias exausto sob o zimbro',
  biblico_referencia = '1 Reis 19:1-8',
  biblico_versiculo = 'Basta, Senhor; toma agora a minha vida, pois não sou melhor do que meus pais. E deitou-se, e dormiu.',
  biblico_teaser = 'Depois da maior vitória pública da própria vida, ele desabou de exaustão pedindo para morrer — e a primeira resposta foi comida e sono.',
  biblico_contexto = 'Elias acabou de vencer, sozinho, um confronto público espetacular contra quatrocentos e cinquenta profetas de Baal no monte Carmelo, provando diante de todo o povo o poder de Deus através de fogo consumindo um sacrifício encharcado de água. Horas depois, a rainha Jezabel jura matá-lo em até vinte e quatro horas.',
  biblico_capitulo = 'Elias foge, andando um dia inteiro de jornada sozinho pelo deserto, e se senta debaixo de um zimbro — um pequeno arbusto, mal capaz de oferecer sombra real, escolhido provavelmente pela exaustão total, sem energia para buscar algo melhor. Sua oração ali não pede vitória nem direção: "basta, Senhor; toma agora a minha vida, pois não sou melhor do que meus pais" — um pedido direto de morte, vindo do mesmo profeta que horas antes tinha demonstrado o poder de Deus da forma mais pública possível. O texto então registra, sem pressa, uma sequência física de cuidado: "deitou-se, e dormiu"; um anjo o toca e diz "levanta-te, e come", e há "à sua cabeceira um bolo cozido sobre as brasas, e um jarro de água"; ele come, bebe, e volta a dormir. O anjo o toca uma segunda vez, repetindo a instrução — "levanta-te, e come; porque o caminho é demasiado longo para ti" — como se uma rodada de descanso não tivesse sido suficiente, e uma segunda fosse necessária antes de qualquer missão nova. Só depois dessa dupla provisão de comida e sono, "com a força daquela comida caminhou quarenta dias e quarenta noites, até Horebe, o monte de Deus" — onde finalmente ocorre o encontro na voz mansa e delicada, e uma nova missão é dada a Elias.',
  biblico_aplicacao = 'A primeira resposta de Deus ao esgotamento de Elias não é um discurso motivacional nem uma repreensão por desanimar depois de uma vitória tão grande — é comida, água, e permissão para dormir, duas vezes seguidas, antes de qualquer palavra ou missão nova ser oferecida. O texto trata o esgotamento físico como necessidade real e legítima, tratada em sua própria ordem, antes de qualquer resposta espiritual ser exigida.',
  biblico_conexao = 'Mateus 11:28 estende o mesmo convite de descanso: "vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei". Marcos 6:31 mostra Jesus dando a mesma instrução prática aos discípulos exaustos: "vinde vós [...] e repousai um pouco". Salmos 127:2 lembra que Deus "dá aos seus amados o sono".'
where slug = 'esgotamento';

update public.feelings set
  biblico_nome = 'Pedro chora amargamente',
  biblico_referencia = 'Mateus 26:31-35, 69-75',
  biblico_versiculo = 'E, lembrando-se Pedro das palavras de Jesus [...] saiu, e chorou amargamente.',
  biblico_teaser = 'Ele tinha prometido nunca abandonar Jesus, mesmo que todos os outros o fizessem — e negou conhecê-lo três vezes antes do galo cantar.',
  biblico_contexto = 'Na última ceia, Jesus avisa que todos os discípulos se escandalizariam naquela noite, citando uma profecia sobre o pastor sendo ferido e as ovelhas se dispersando. Pedro reage com uma promessa forte e específica: "ainda que todos se escandalizem em ti, eu nunca me escandalizarei." Jesus responde prevendo que, antes do galo cantar, Pedro o negaria três vezes; Pedro insiste ainda mais: "ainda que me seja necessário morrer contigo, não te negarei."',
  biblico_capitulo = 'Horas depois, com Jesus preso e sendo julgado, Pedro o segue "de longe" até o pátio do sumo sacerdote, sentando-se ali "para ver o fim". Uma criada o reconhece como um dos que estava com Jesus; Pedro nega diante de todos: "não sei o que dizes." Ele se afasta para o alpendre, e outra pessoa o reconhece novamente; ele nega pela segunda vez, agora "com juramento: não conheço tal homem." Pouco depois, os que estavam ali insistem, notando seu sotaque galileu; Pedro nega pela terceira vez, começando "a praguejar e a jurar, dizendo: não conheço esse homem" — uma negação cada vez mais intensa e categórica, não mais fraca. Imediatamente depois dessa terceira negação, "o galo cantou. E Pedro lembrou-se das palavras de Jesus" — a mesma previsão que ele tinha rejeitado horas antes com tanta convicção. O texto registra a reação sem suavizar: "e, saindo, chorou amargamente." Não há registro, nesse capítulo, de nenhuma palavra de conforto imediato, nenhuma justificativa oferecida por Pedro — só o choro, sozinho, depois de perceber o tamanho da distância entre a promessa feita e a ação tomada.',
  biblico_aplicacao = 'A sensação de fracasso de Pedro nasce exatamente do contraste entre a certeza que ele tinha sobre a própria lealdade e a rapidez com que ela cedeu sob pressão real. O texto não apressa uma resolução — permite que o choro amargo simplesmente exista, sem minimizar a queda nem tentar consertá-la na mesma cena.',
  biblico_conexao = 'João 21:15-19, já visto no sentimento de dificuldade de recomeçar, mostra o que vem depois desse choro: a mesma pessoa, restaurada e reenviada, sem precisar apagar o que aconteceu. Provérbios 24:16 nomeia o padrão maior: "sete vezes cai o justo, e se levanta". Lucas 22:31-32 revela que Jesus já tinha orado por Pedro antes da queda acontecer, para que sua "fé não desfalecesse".'
where slug = 'sensacao-de-fracasso';
